/*
FOSSA API

Testing BinaryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package fossa

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/RobertKielty/fossa-go"
)

func Test_fossa_BinaryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BinaryAPIService GetReleaseComponentsCount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var releaseGroupId float32
		var releaseId float32

		resp, httpRes, err := apiClient.BinaryAPI.GetReleaseComponentsCount(context.Background(), releaseGroupId, releaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BinaryAPIService GetReleaseComponentsPaths", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var releaseGroupId float32
		var releaseId float32

		resp, httpRes, err := apiClient.BinaryAPI.GetReleaseComponentsPaths(context.Background(), releaseGroupId, releaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BinaryAPIService GetReleaseDependencyConfidence", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var releaseId float32

		resp, httpRes, err := apiClient.BinaryAPI.GetReleaseDependencyConfidence(context.Background(), releaseId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BinaryAPIService GetRevisionComponentMatches", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var revisionLocator string
		var componentId string

		resp, httpRes, err := apiClient.BinaryAPI.GetRevisionComponentMatches(context.Background(), revisionLocator, componentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BinaryAPIService GetRevisionComponentsCount", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var revisionLocator string

		resp, httpRes, err := apiClient.BinaryAPI.GetRevisionComponentsCount(context.Background(), revisionLocator).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BinaryAPIService GetRevisionComponentsPaths", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var revisionLocator string

		resp, httpRes, err := apiClient.BinaryAPI.GetRevisionComponentsPaths(context.Background(), revisionLocator).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BinaryAPIService GetRevisionDependencyComponents", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var revisionLocator string
		var dependencyLocator string

		resp, httpRes, err := apiClient.BinaryAPI.GetRevisionDependencyComponents(context.Background(), revisionLocator, dependencyLocator).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BinaryAPIService GetRevisionDependencyConfidence", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var revisionLocator string

		resp, httpRes, err := apiClient.BinaryAPI.GetRevisionDependencyConfidence(context.Background(), revisionLocator).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BinaryAPIService GetSingleReleaseDependencyConfidence", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var releaseId float32
		var dependencyLocator string

		resp, httpRes, err := apiClient.BinaryAPI.GetSingleReleaseDependencyConfidence(context.Background(), releaseId, dependencyLocator).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BinaryAPIService GetSingleRevisionDependencyConfidence", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var revisionLocator string
		var dependencyLocator string

		resp, httpRes, err := apiClient.BinaryAPI.GetSingleRevisionDependencyConfidence(context.Background(), revisionLocator, dependencyLocator).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
