/*
FOSSA API

Testing SnippetsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package fossa

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/RobertKielty/fossa-go"
)

func Test_fossa_SnippetsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SnippetsAPIService GetComparedSnippetPaths", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var locator string
		var olderRevisionLocator string
		var status string

		resp, httpRes, err := apiClient.SnippetsAPI.GetComparedSnippetPaths(context.Background(), locator, olderRevisionLocator, status).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnippetsAPIService GetComparedSnippets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var locator string
		var olderRevisionLocator string
		var status string

		resp, httpRes, err := apiClient.SnippetsAPI.GetComparedSnippets(context.Background(), locator, olderRevisionLocator, status).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnippetsAPIService GetSnippetById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var locator string
		var snippetId string

		resp, httpRes, err := apiClient.SnippetsAPI.GetSnippetById(context.Background(), locator, snippetId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnippetsAPIService GetSnippetMatchDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var locator string
		var snippetId string
		var path string

		resp, httpRes, err := apiClient.SnippetsAPI.GetSnippetMatchDetails(context.Background(), locator, snippetId, path).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnippetsAPIService GetSnippetPaths", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var locator string

		resp, httpRes, err := apiClient.SnippetsAPI.GetSnippetPaths(context.Background(), locator).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnippetsAPIService GetSnippets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var locator string

		resp, httpRes, err := apiClient.SnippetsAPI.GetSnippets(context.Background(), locator).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnippetsAPIService RejectSnippets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var locator string

		httpRes, err := apiClient.SnippetsAPI.RejectSnippets(context.Background(), locator).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SnippetsAPIService UnrejectSnippets", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var locator string

		httpRes, err := apiClient.SnippetsAPI.UnrejectSnippets(context.Background(), locator).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
