/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.30.21
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOIDCProviderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOIDCProviderRequest{}

// UpdateOIDCProviderRequest struct for UpdateOIDCProviderRequest
type UpdateOIDCProviderRequest struct {
	// Array of thumbprints for certificate validation
	Thumbprints []string `json:"thumbprints"`
}

type _UpdateOIDCProviderRequest UpdateOIDCProviderRequest

// NewUpdateOIDCProviderRequest instantiates a new UpdateOIDCProviderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOIDCProviderRequest(thumbprints []string) *UpdateOIDCProviderRequest {
	this := UpdateOIDCProviderRequest{}
	this.Thumbprints = thumbprints
	return &this
}

// NewUpdateOIDCProviderRequestWithDefaults instantiates a new UpdateOIDCProviderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOIDCProviderRequestWithDefaults() *UpdateOIDCProviderRequest {
	this := UpdateOIDCProviderRequest{}
	return &this
}

// GetThumbprints returns the Thumbprints field value
func (o *UpdateOIDCProviderRequest) GetThumbprints() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Thumbprints
}

// GetThumbprintsOk returns a tuple with the Thumbprints field value
// and a boolean to check if the value has been set.
func (o *UpdateOIDCProviderRequest) GetThumbprintsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Thumbprints, true
}

// SetThumbprints sets field value
func (o *UpdateOIDCProviderRequest) SetThumbprints(v []string) {
	o.Thumbprints = v
}

func (o UpdateOIDCProviderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOIDCProviderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["thumbprints"] = o.Thumbprints
	return toSerialize, nil
}

func (o *UpdateOIDCProviderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"thumbprints",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOIDCProviderRequest := _UpdateOIDCProviderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOIDCProviderRequest)

	if err != nil {
		return err
	}

	*o = UpdateOIDCProviderRequest(varUpdateOIDCProviderRequest)

	return err
}

type NullableUpdateOIDCProviderRequest struct {
	value *UpdateOIDCProviderRequest
	isSet bool
}

func (v NullableUpdateOIDCProviderRequest) Get() *UpdateOIDCProviderRequest {
	return v.value
}

func (v *NullableUpdateOIDCProviderRequest) Set(val *UpdateOIDCProviderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOIDCProviderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOIDCProviderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOIDCProviderRequest(val *UpdateOIDCProviderRequest) *NullableUpdateOIDCProviderRequest {
	return &NullableUpdateOIDCProviderRequest{value: val, isSet: true}
}

func (v NullableUpdateOIDCProviderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOIDCProviderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


