/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.28.61
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"time"
)

// checks if the DeprecatedGetReleaseGroupReleases200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeprecatedGetReleaseGroupReleases200ResponseInner{}

// DeprecatedGetReleaseGroupReleases200ResponseInner struct for DeprecatedGetReleaseGroupReleases200ResponseInner
type DeprecatedGetReleaseGroupReleases200ResponseInner struct {
	Id *int32 `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	OrganizationId *int32 `json:"organizationId,omitempty"`
	PolicyId NullableInt32 `json:"policyId,omitempty"`
	SecurityPolicyId NullableInt32 `json:"securityPolicyId,omitempty"`
	QualityPolicyId NullableInt32 `json:"qualityPolicyId,omitempty"`
	PublicOnPortal *bool `json:"publicOnPortal,omitempty"`
	ReportCustomText NullableString `json:"reportCustomText,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	Projects []GetReleaseGroupById200ResponseAllOfProjectsInner `json:"projects,omitempty"`
}

// NewDeprecatedGetReleaseGroupReleases200ResponseInner instantiates a new DeprecatedGetReleaseGroupReleases200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeprecatedGetReleaseGroupReleases200ResponseInner() *DeprecatedGetReleaseGroupReleases200ResponseInner {
	this := DeprecatedGetReleaseGroupReleases200ResponseInner{}
	return &this
}

// NewDeprecatedGetReleaseGroupReleases200ResponseInnerWithDefaults instantiates a new DeprecatedGetReleaseGroupReleases200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeprecatedGetReleaseGroupReleases200ResponseInnerWithDefaults() *DeprecatedGetReleaseGroupReleases200ResponseInner {
	this := DeprecatedGetReleaseGroupReleases200ResponseInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetId(v int32) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetTitle(v string) {
	o.Title = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetOrganizationId() int32 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int32
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetOrganizationIdOk() (*int32, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int32 and assigns it to the OrganizationId field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetOrganizationId(v int32) {
	o.OrganizationId = &v
}

// GetPolicyId returns the PolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetPolicyId() int32 {
	if o == nil || IsNil(o.PolicyId.Get()) {
		var ret int32
		return ret
	}
	return *o.PolicyId.Get()
}

// GetPolicyIdOk returns a tuple with the PolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetPolicyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PolicyId.Get(), o.PolicyId.IsSet()
}

// HasPolicyId returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasPolicyId() bool {
	if o != nil && o.PolicyId.IsSet() {
		return true
	}

	return false
}

// SetPolicyId gets a reference to the given NullableInt32 and assigns it to the PolicyId field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetPolicyId(v int32) {
	o.PolicyId.Set(&v)
}
// SetPolicyIdNil sets the value for PolicyId to be an explicit nil
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetPolicyIdNil() {
	o.PolicyId.Set(nil)
}

// UnsetPolicyId ensures that no value is present for PolicyId, not even an explicit nil
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) UnsetPolicyId() {
	o.PolicyId.Unset()
}

// GetSecurityPolicyId returns the SecurityPolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetSecurityPolicyId() int32 {
	if o == nil || IsNil(o.SecurityPolicyId.Get()) {
		var ret int32
		return ret
	}
	return *o.SecurityPolicyId.Get()
}

// GetSecurityPolicyIdOk returns a tuple with the SecurityPolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetSecurityPolicyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecurityPolicyId.Get(), o.SecurityPolicyId.IsSet()
}

// HasSecurityPolicyId returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasSecurityPolicyId() bool {
	if o != nil && o.SecurityPolicyId.IsSet() {
		return true
	}

	return false
}

// SetSecurityPolicyId gets a reference to the given NullableInt32 and assigns it to the SecurityPolicyId field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetSecurityPolicyId(v int32) {
	o.SecurityPolicyId.Set(&v)
}
// SetSecurityPolicyIdNil sets the value for SecurityPolicyId to be an explicit nil
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetSecurityPolicyIdNil() {
	o.SecurityPolicyId.Set(nil)
}

// UnsetSecurityPolicyId ensures that no value is present for SecurityPolicyId, not even an explicit nil
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) UnsetSecurityPolicyId() {
	o.SecurityPolicyId.Unset()
}

// GetQualityPolicyId returns the QualityPolicyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetQualityPolicyId() int32 {
	if o == nil || IsNil(o.QualityPolicyId.Get()) {
		var ret int32
		return ret
	}
	return *o.QualityPolicyId.Get()
}

// GetQualityPolicyIdOk returns a tuple with the QualityPolicyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetQualityPolicyIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.QualityPolicyId.Get(), o.QualityPolicyId.IsSet()
}

// HasQualityPolicyId returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasQualityPolicyId() bool {
	if o != nil && o.QualityPolicyId.IsSet() {
		return true
	}

	return false
}

// SetQualityPolicyId gets a reference to the given NullableInt32 and assigns it to the QualityPolicyId field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetQualityPolicyId(v int32) {
	o.QualityPolicyId.Set(&v)
}
// SetQualityPolicyIdNil sets the value for QualityPolicyId to be an explicit nil
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetQualityPolicyIdNil() {
	o.QualityPolicyId.Set(nil)
}

// UnsetQualityPolicyId ensures that no value is present for QualityPolicyId, not even an explicit nil
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) UnsetQualityPolicyId() {
	o.QualityPolicyId.Unset()
}

// GetPublicOnPortal returns the PublicOnPortal field value if set, zero value otherwise.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetPublicOnPortal() bool {
	if o == nil || IsNil(o.PublicOnPortal) {
		var ret bool
		return ret
	}
	return *o.PublicOnPortal
}

// GetPublicOnPortalOk returns a tuple with the PublicOnPortal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetPublicOnPortalOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicOnPortal) {
		return nil, false
	}
	return o.PublicOnPortal, true
}

// HasPublicOnPortal returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasPublicOnPortal() bool {
	if o != nil && !IsNil(o.PublicOnPortal) {
		return true
	}

	return false
}

// SetPublicOnPortal gets a reference to the given bool and assigns it to the PublicOnPortal field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetPublicOnPortal(v bool) {
	o.PublicOnPortal = &v
}

// GetReportCustomText returns the ReportCustomText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetReportCustomText() string {
	if o == nil || IsNil(o.ReportCustomText.Get()) {
		var ret string
		return ret
	}
	return *o.ReportCustomText.Get()
}

// GetReportCustomTextOk returns a tuple with the ReportCustomText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetReportCustomTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReportCustomText.Get(), o.ReportCustomText.IsSet()
}

// HasReportCustomText returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasReportCustomText() bool {
	if o != nil && o.ReportCustomText.IsSet() {
		return true
	}

	return false
}

// SetReportCustomText gets a reference to the given NullableString and assigns it to the ReportCustomText field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetReportCustomText(v string) {
	o.ReportCustomText.Set(&v)
}
// SetReportCustomTextNil sets the value for ReportCustomText to be an explicit nil
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetReportCustomTextNil() {
	o.ReportCustomText.Set(nil)
}

// UnsetReportCustomText ensures that no value is present for ReportCustomText, not even an explicit nil
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) UnsetReportCustomText() {
	o.ReportCustomText.Unset()
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetProjects returns the Projects field value if set, zero value otherwise.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetProjects() []GetReleaseGroupById200ResponseAllOfProjectsInner {
	if o == nil || IsNil(o.Projects) {
		var ret []GetReleaseGroupById200ResponseAllOfProjectsInner
		return ret
	}
	return o.Projects
}

// GetProjectsOk returns a tuple with the Projects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) GetProjectsOk() ([]GetReleaseGroupById200ResponseAllOfProjectsInner, bool) {
	if o == nil || IsNil(o.Projects) {
		return nil, false
	}
	return o.Projects, true
}

// HasProjects returns a boolean if a field has been set.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) HasProjects() bool {
	if o != nil && !IsNil(o.Projects) {
		return true
	}

	return false
}

// SetProjects gets a reference to the given []GetReleaseGroupById200ResponseAllOfProjectsInner and assigns it to the Projects field.
func (o *DeprecatedGetReleaseGroupReleases200ResponseInner) SetProjects(v []GetReleaseGroupById200ResponseAllOfProjectsInner) {
	o.Projects = v
}

func (o DeprecatedGetReleaseGroupReleases200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeprecatedGetReleaseGroupReleases200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if o.PolicyId.IsSet() {
		toSerialize["policyId"] = o.PolicyId.Get()
	}
	if o.SecurityPolicyId.IsSet() {
		toSerialize["securityPolicyId"] = o.SecurityPolicyId.Get()
	}
	if o.QualityPolicyId.IsSet() {
		toSerialize["qualityPolicyId"] = o.QualityPolicyId.Get()
	}
	if !IsNil(o.PublicOnPortal) {
		toSerialize["publicOnPortal"] = o.PublicOnPortal
	}
	if o.ReportCustomText.IsSet() {
		toSerialize["reportCustomText"] = o.ReportCustomText.Get()
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.Projects) {
		toSerialize["projects"] = o.Projects
	}
	return toSerialize, nil
}

type NullableDeprecatedGetReleaseGroupReleases200ResponseInner struct {
	value *DeprecatedGetReleaseGroupReleases200ResponseInner
	isSet bool
}

func (v NullableDeprecatedGetReleaseGroupReleases200ResponseInner) Get() *DeprecatedGetReleaseGroupReleases200ResponseInner {
	return v.value
}

func (v *NullableDeprecatedGetReleaseGroupReleases200ResponseInner) Set(val *DeprecatedGetReleaseGroupReleases200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDeprecatedGetReleaseGroupReleases200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDeprecatedGetReleaseGroupReleases200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeprecatedGetReleaseGroupReleases200ResponseInner(val *DeprecatedGetReleaseGroupReleases200ResponseInner) *NullableDeprecatedGetReleaseGroupReleases200ResponseInner {
	return &NullableDeprecatedGetReleaseGroupReleases200ResponseInner{value: val, isSet: true}
}

func (v NullableDeprecatedGetReleaseGroupReleases200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeprecatedGetReleaseGroupReleases200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


