/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.64
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner{}

// GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner struct for GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner
type GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner struct {
	// The actual code line text
	Line string `json:"line"`
	// The line number in the file
	LineNumber int32 `json:"lineNumber"`
	// Whether this line should be highlighted as part of the match
	IsHighlighted bool `json:"isHighlighted"`
}

type _GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner

// NewGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner instantiates a new GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner(line string, lineNumber int32, isHighlighted bool) *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner {
	this := GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner{}
	this.Line = line
	this.LineNumber = lineNumber
	this.IsHighlighted = isHighlighted
	return &this
}

// NewGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInnerWithDefaults instantiates a new GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInnerWithDefaults() *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner {
	this := GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner{}
	return &this
}

// GetLine returns the Line field value
func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) GetLine() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Line
}

// GetLineOk returns a tuple with the Line field value
// and a boolean to check if the value has been set.
func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) GetLineOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Line, true
}

// SetLine sets field value
func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) SetLine(v string) {
	o.Line = v
}

// GetLineNumber returns the LineNumber field value
func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) GetLineNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.LineNumber
}

// GetLineNumberOk returns a tuple with the LineNumber field value
// and a boolean to check if the value has been set.
func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) GetLineNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LineNumber, true
}

// SetLineNumber sets field value
func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) SetLineNumber(v int32) {
	o.LineNumber = v
}

// GetIsHighlighted returns the IsHighlighted field value
func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) GetIsHighlighted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsHighlighted
}

// GetIsHighlightedOk returns a tuple with the IsHighlighted field value
// and a boolean to check if the value has been set.
func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) GetIsHighlightedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsHighlighted, true
}

// SetIsHighlighted sets field value
func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) SetIsHighlighted(v bool) {
	o.IsHighlighted = v
}

func (o GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["line"] = o.Line
	toSerialize["lineNumber"] = o.LineNumber
	toSerialize["isHighlighted"] = o.IsHighlighted
	return toSerialize, nil
}

func (o *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"line",
		"lineNumber",
		"isHighlighted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner := _GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner)

	if err != nil {
		return err
	}

	*o = GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner(varGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner)

	return err
}

type NullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner struct {
	value *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner
	isSet bool
}

func (v NullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) Get() *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner {
	return v.value
}

func (v *NullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) Set(val *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner(val *GetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) *NullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner {
	return &NullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner{value: val, isSet: true}
}

func (v NullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSnippetMatchDetails200ResponseMatchDetailsAllOfReferenceCodeInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


