/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.33.20
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"time"
)

// checks if the GetIssue200ResponseOneOfAllOfCustomRiskScore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIssue200ResponseOneOfAllOfCustomRiskScore{}

// GetIssue200ResponseOneOfAllOfCustomRiskScore Optional custom risk score for the vulnerability. Not available for global scope queries. 
type GetIssue200ResponseOneOfAllOfCustomRiskScore struct {
	Score *float32 `json:"score,omitempty"`
	Reason *string `json:"reason,omitempty"`
	CreatedBy *string `json:"createdBy,omitempty"`
	UpdatedBy *string `json:"updatedBy,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewGetIssue200ResponseOneOfAllOfCustomRiskScore instantiates a new GetIssue200ResponseOneOfAllOfCustomRiskScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIssue200ResponseOneOfAllOfCustomRiskScore() *GetIssue200ResponseOneOfAllOfCustomRiskScore {
	this := GetIssue200ResponseOneOfAllOfCustomRiskScore{}
	return &this
}

// NewGetIssue200ResponseOneOfAllOfCustomRiskScoreWithDefaults instantiates a new GetIssue200ResponseOneOfAllOfCustomRiskScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIssue200ResponseOneOfAllOfCustomRiskScoreWithDefaults() *GetIssue200ResponseOneOfAllOfCustomRiskScore {
	this := GetIssue200ResponseOneOfAllOfCustomRiskScore{}
	return &this
}

// GetScore returns the Score field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetScore() float32 {
	if o == nil || IsNil(o.Score) {
		var ret float32
		return ret
	}
	return *o.Score
}

// GetScoreOk returns a tuple with the Score field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetScoreOk() (*float32, bool) {
	if o == nil || IsNil(o.Score) {
		return nil, false
	}
	return o.Score, true
}

// HasScore returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) HasScore() bool {
	if o != nil && !IsNil(o.Score) {
		return true
	}

	return false
}

// SetScore gets a reference to the given float32 and assigns it to the Score field.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) SetScore(v float32) {
	o.Score = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) SetReason(v string) {
	o.Reason = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy) {
		var ret string
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetCreatedByOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given string and assigns it to the CreatedBy field.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) SetCreatedBy(v string) {
	o.CreatedBy = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetUpdatedBy() string {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret string
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetUpdatedByOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given string and assigns it to the UpdatedBy field.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) SetUpdatedBy(v string) {
	o.UpdatedBy = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetIssue200ResponseOneOfAllOfCustomRiskScore) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o GetIssue200ResponseOneOfAllOfCustomRiskScore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIssue200ResponseOneOfAllOfCustomRiskScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Score) {
		toSerialize["score"] = o.Score
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["createdBy"] = o.CreatedBy
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updatedBy"] = o.UpdatedBy
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGetIssue200ResponseOneOfAllOfCustomRiskScore struct {
	value *GetIssue200ResponseOneOfAllOfCustomRiskScore
	isSet bool
}

func (v NullableGetIssue200ResponseOneOfAllOfCustomRiskScore) Get() *GetIssue200ResponseOneOfAllOfCustomRiskScore {
	return v.value
}

func (v *NullableGetIssue200ResponseOneOfAllOfCustomRiskScore) Set(val *GetIssue200ResponseOneOfAllOfCustomRiskScore) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIssue200ResponseOneOfAllOfCustomRiskScore) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIssue200ResponseOneOfAllOfCustomRiskScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIssue200ResponseOneOfAllOfCustomRiskScore(val *GetIssue200ResponseOneOfAllOfCustomRiskScore) *NullableGetIssue200ResponseOneOfAllOfCustomRiskScore {
	return &NullableGetIssue200ResponseOneOfAllOfCustomRiskScore{value: val, isSet: true}
}

func (v NullableGetIssue200ResponseOneOfAllOfCustomRiskScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIssue200ResponseOneOfAllOfCustomRiskScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


