/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.30.21
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue - The claim value
type CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue struct {
	Bool *bool
	Float32 *float32
	String *string
}

// boolAsCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue is a convenience function that returns bool wrapped in CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue
func BoolAsCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue(v *bool) CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue {
	return CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue{
		Bool: v,
	}
}

// float32AsCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue is a convenience function that returns float32 wrapped in CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue
func Float32AsCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue(v *float32) CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue {
	return CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue{
		Float32: v,
	}
}

// stringAsCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue is a convenience function that returns string wrapped in CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue
func StringAsCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue(v *string) CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue {
	return CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			if err = validator.Validate(dst.Float32); err != nil {
				dst.Float32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.Float32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) GetActualInstanceValue() (interface{}) {
	if obj.Bool != nil {
		return *obj.Bool
	}

	if obj.Float32 != nil {
		return *obj.Float32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue struct {
	value *CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue
	isSet bool
}

func (v NullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) Get() *CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue {
	return v.value
}

func (v *NullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) Set(val *CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue(val *CreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) *NullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue {
	return &NullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue{value: val, isSet: true}
}

func (v NullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOIDCTrustRelationshipRequestRequiredClaimsInnerValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


