/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.39
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"time"
)

// checks if the GetRevisionAttributionEmailV2200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRevisionAttributionEmailV2200Response{}

// GetRevisionAttributionEmailV2200Response Metadata describing a background task that has been queued for processing.
type GetRevisionAttributionEmailV2200Response struct {
	// Unique identifier for the task
	Id *int32 `json:"id,omitempty"`
	// Name of the task being run
	Task *string `json:"task,omitempty"`
	// Token used to poll for the task's status and result
	JobToken *string `json:"jobToken,omitempty"`
	// Current status of the task
	Status *string `json:"status,omitempty"`
	// Number of times the task has been attempted
	AttemptNumber *int32 `json:"attempt_number,omitempty"`
	// Maximum number of retries permitted for the task
	MaxRetries NullableInt32 `json:"maxRetries,omitempty"`
	// When the task started running, or null if it has not started
	Started NullableTime `json:"started,omitempty"`
	// When the task finished, or null if it has not finished
	Finished NullableTime `json:"finished,omitempty"`
	// When the task is scheduled to start, or null
	ScheduledStartTime NullableTime `json:"scheduledStartTime,omitempty"`
	// Identifier of the pod running the task, or null
	Pod NullableString `json:"pod,omitempty"`
	// Task-specific context payload
	Context map[string]interface{} `json:"context,omitempty"`
	// When the task record was created
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// When the task record was last updated
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewGetRevisionAttributionEmailV2200Response instantiates a new GetRevisionAttributionEmailV2200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRevisionAttributionEmailV2200Response() *GetRevisionAttributionEmailV2200Response {
	this := GetRevisionAttributionEmailV2200Response{}
	return &this
}

// NewGetRevisionAttributionEmailV2200ResponseWithDefaults instantiates a new GetRevisionAttributionEmailV2200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRevisionAttributionEmailV2200ResponseWithDefaults() *GetRevisionAttributionEmailV2200Response {
	this := GetRevisionAttributionEmailV2200Response{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetRevisionAttributionEmailV2200Response) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionAttributionEmailV2200Response) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetRevisionAttributionEmailV2200Response) SetId(v int32) {
	o.Id = &v
}

// GetTask returns the Task field value if set, zero value otherwise.
func (o *GetRevisionAttributionEmailV2200Response) GetTask() string {
	if o == nil || IsNil(o.Task) {
		var ret string
		return ret
	}
	return *o.Task
}

// GetTaskOk returns a tuple with the Task field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionAttributionEmailV2200Response) GetTaskOk() (*string, bool) {
	if o == nil || IsNil(o.Task) {
		return nil, false
	}
	return o.Task, true
}

// HasTask returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasTask() bool {
	if o != nil && !IsNil(o.Task) {
		return true
	}

	return false
}

// SetTask gets a reference to the given string and assigns it to the Task field.
func (o *GetRevisionAttributionEmailV2200Response) SetTask(v string) {
	o.Task = &v
}

// GetJobToken returns the JobToken field value if set, zero value otherwise.
func (o *GetRevisionAttributionEmailV2200Response) GetJobToken() string {
	if o == nil || IsNil(o.JobToken) {
		var ret string
		return ret
	}
	return *o.JobToken
}

// GetJobTokenOk returns a tuple with the JobToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionAttributionEmailV2200Response) GetJobTokenOk() (*string, bool) {
	if o == nil || IsNil(o.JobToken) {
		return nil, false
	}
	return o.JobToken, true
}

// HasJobToken returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasJobToken() bool {
	if o != nil && !IsNil(o.JobToken) {
		return true
	}

	return false
}

// SetJobToken gets a reference to the given string and assigns it to the JobToken field.
func (o *GetRevisionAttributionEmailV2200Response) SetJobToken(v string) {
	o.JobToken = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetRevisionAttributionEmailV2200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionAttributionEmailV2200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetRevisionAttributionEmailV2200Response) SetStatus(v string) {
	o.Status = &v
}

// GetAttemptNumber returns the AttemptNumber field value if set, zero value otherwise.
func (o *GetRevisionAttributionEmailV2200Response) GetAttemptNumber() int32 {
	if o == nil || IsNil(o.AttemptNumber) {
		var ret int32
		return ret
	}
	return *o.AttemptNumber
}

// GetAttemptNumberOk returns a tuple with the AttemptNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionAttributionEmailV2200Response) GetAttemptNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.AttemptNumber) {
		return nil, false
	}
	return o.AttemptNumber, true
}

// HasAttemptNumber returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasAttemptNumber() bool {
	if o != nil && !IsNil(o.AttemptNumber) {
		return true
	}

	return false
}

// SetAttemptNumber gets a reference to the given int32 and assigns it to the AttemptNumber field.
func (o *GetRevisionAttributionEmailV2200Response) SetAttemptNumber(v int32) {
	o.AttemptNumber = &v
}

// GetMaxRetries returns the MaxRetries field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevisionAttributionEmailV2200Response) GetMaxRetries() int32 {
	if o == nil || IsNil(o.MaxRetries.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxRetries.Get()
}

// GetMaxRetriesOk returns a tuple with the MaxRetries field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevisionAttributionEmailV2200Response) GetMaxRetriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxRetries.Get(), o.MaxRetries.IsSet()
}

// HasMaxRetries returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasMaxRetries() bool {
	if o != nil && o.MaxRetries.IsSet() {
		return true
	}

	return false
}

// SetMaxRetries gets a reference to the given NullableInt32 and assigns it to the MaxRetries field.
func (o *GetRevisionAttributionEmailV2200Response) SetMaxRetries(v int32) {
	o.MaxRetries.Set(&v)
}
// SetMaxRetriesNil sets the value for MaxRetries to be an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) SetMaxRetriesNil() {
	o.MaxRetries.Set(nil)
}

// UnsetMaxRetries ensures that no value is present for MaxRetries, not even an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) UnsetMaxRetries() {
	o.MaxRetries.Unset()
}

// GetStarted returns the Started field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevisionAttributionEmailV2200Response) GetStarted() time.Time {
	if o == nil || IsNil(o.Started.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Started.Get()
}

// GetStartedOk returns a tuple with the Started field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevisionAttributionEmailV2200Response) GetStartedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Started.Get(), o.Started.IsSet()
}

// HasStarted returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasStarted() bool {
	if o != nil && o.Started.IsSet() {
		return true
	}

	return false
}

// SetStarted gets a reference to the given NullableTime and assigns it to the Started field.
func (o *GetRevisionAttributionEmailV2200Response) SetStarted(v time.Time) {
	o.Started.Set(&v)
}
// SetStartedNil sets the value for Started to be an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) SetStartedNil() {
	o.Started.Set(nil)
}

// UnsetStarted ensures that no value is present for Started, not even an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) UnsetStarted() {
	o.Started.Unset()
}

// GetFinished returns the Finished field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevisionAttributionEmailV2200Response) GetFinished() time.Time {
	if o == nil || IsNil(o.Finished.Get()) {
		var ret time.Time
		return ret
	}
	return *o.Finished.Get()
}

// GetFinishedOk returns a tuple with the Finished field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevisionAttributionEmailV2200Response) GetFinishedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Finished.Get(), o.Finished.IsSet()
}

// HasFinished returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasFinished() bool {
	if o != nil && o.Finished.IsSet() {
		return true
	}

	return false
}

// SetFinished gets a reference to the given NullableTime and assigns it to the Finished field.
func (o *GetRevisionAttributionEmailV2200Response) SetFinished(v time.Time) {
	o.Finished.Set(&v)
}
// SetFinishedNil sets the value for Finished to be an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) SetFinishedNil() {
	o.Finished.Set(nil)
}

// UnsetFinished ensures that no value is present for Finished, not even an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) UnsetFinished() {
	o.Finished.Unset()
}

// GetScheduledStartTime returns the ScheduledStartTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevisionAttributionEmailV2200Response) GetScheduledStartTime() time.Time {
	if o == nil || IsNil(o.ScheduledStartTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ScheduledStartTime.Get()
}

// GetScheduledStartTimeOk returns a tuple with the ScheduledStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevisionAttributionEmailV2200Response) GetScheduledStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ScheduledStartTime.Get(), o.ScheduledStartTime.IsSet()
}

// HasScheduledStartTime returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasScheduledStartTime() bool {
	if o != nil && o.ScheduledStartTime.IsSet() {
		return true
	}

	return false
}

// SetScheduledStartTime gets a reference to the given NullableTime and assigns it to the ScheduledStartTime field.
func (o *GetRevisionAttributionEmailV2200Response) SetScheduledStartTime(v time.Time) {
	o.ScheduledStartTime.Set(&v)
}
// SetScheduledStartTimeNil sets the value for ScheduledStartTime to be an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) SetScheduledStartTimeNil() {
	o.ScheduledStartTime.Set(nil)
}

// UnsetScheduledStartTime ensures that no value is present for ScheduledStartTime, not even an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) UnsetScheduledStartTime() {
	o.ScheduledStartTime.Unset()
}

// GetPod returns the Pod field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevisionAttributionEmailV2200Response) GetPod() string {
	if o == nil || IsNil(o.Pod.Get()) {
		var ret string
		return ret
	}
	return *o.Pod.Get()
}

// GetPodOk returns a tuple with the Pod field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevisionAttributionEmailV2200Response) GetPodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pod.Get(), o.Pod.IsSet()
}

// HasPod returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasPod() bool {
	if o != nil && o.Pod.IsSet() {
		return true
	}

	return false
}

// SetPod gets a reference to the given NullableString and assigns it to the Pod field.
func (o *GetRevisionAttributionEmailV2200Response) SetPod(v string) {
	o.Pod.Set(&v)
}
// SetPodNil sets the value for Pod to be an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) SetPodNil() {
	o.Pod.Set(nil)
}

// UnsetPod ensures that no value is present for Pod, not even an explicit nil
func (o *GetRevisionAttributionEmailV2200Response) UnsetPod() {
	o.Pod.Unset()
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *GetRevisionAttributionEmailV2200Response) GetContext() map[string]interface{} {
	if o == nil || IsNil(o.Context) {
		var ret map[string]interface{}
		return ret
	}
	return o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionAttributionEmailV2200Response) GetContextOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Context) {
		return map[string]interface{}{}, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasContext() bool {
	if o != nil && !IsNil(o.Context) {
		return true
	}

	return false
}

// SetContext gets a reference to the given map[string]interface{} and assigns it to the Context field.
func (o *GetRevisionAttributionEmailV2200Response) SetContext(v map[string]interface{}) {
	o.Context = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetRevisionAttributionEmailV2200Response) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionAttributionEmailV2200Response) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *GetRevisionAttributionEmailV2200Response) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetRevisionAttributionEmailV2200Response) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionAttributionEmailV2200Response) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetRevisionAttributionEmailV2200Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetRevisionAttributionEmailV2200Response) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o GetRevisionAttributionEmailV2200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRevisionAttributionEmailV2200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Task) {
		toSerialize["task"] = o.Task
	}
	if !IsNil(o.JobToken) {
		toSerialize["jobToken"] = o.JobToken
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.AttemptNumber) {
		toSerialize["attempt_number"] = o.AttemptNumber
	}
	if o.MaxRetries.IsSet() {
		toSerialize["maxRetries"] = o.MaxRetries.Get()
	}
	if o.Started.IsSet() {
		toSerialize["started"] = o.Started.Get()
	}
	if o.Finished.IsSet() {
		toSerialize["finished"] = o.Finished.Get()
	}
	if o.ScheduledStartTime.IsSet() {
		toSerialize["scheduledStartTime"] = o.ScheduledStartTime.Get()
	}
	if o.Pod.IsSet() {
		toSerialize["pod"] = o.Pod.Get()
	}
	if !IsNil(o.Context) {
		toSerialize["context"] = o.Context
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGetRevisionAttributionEmailV2200Response struct {
	value *GetRevisionAttributionEmailV2200Response
	isSet bool
}

func (v NullableGetRevisionAttributionEmailV2200Response) Get() *GetRevisionAttributionEmailV2200Response {
	return v.value
}

func (v *NullableGetRevisionAttributionEmailV2200Response) Set(val *GetRevisionAttributionEmailV2200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRevisionAttributionEmailV2200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRevisionAttributionEmailV2200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRevisionAttributionEmailV2200Response(val *GetRevisionAttributionEmailV2200Response) *NullableGetRevisionAttributionEmailV2200Response {
	return &NullableGetRevisionAttributionEmailV2200Response{value: val, isSet: true}
}

func (v NullableGetRevisionAttributionEmailV2200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRevisionAttributionEmailV2200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


