/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.28.61
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the GetIssue200ResponseOneOfAllOfRemediation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIssue200ResponseOneOfAllOfRemediation{}

// GetIssue200ResponseOneOfAllOfRemediation struct for GetIssue200ResponseOneOfAllOfRemediation
type GetIssue200ResponseOneOfAllOfRemediation struct {
	PartialFix *string `json:"partialFix,omitempty"`
	PartialFixDistance *string `json:"partialFixDistance,omitempty"`
	CompleteFix *string `json:"completeFix,omitempty"`
	CompleteFixDistance *string `json:"completeFixDistance,omitempty"`
}

// NewGetIssue200ResponseOneOfAllOfRemediation instantiates a new GetIssue200ResponseOneOfAllOfRemediation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIssue200ResponseOneOfAllOfRemediation() *GetIssue200ResponseOneOfAllOfRemediation {
	this := GetIssue200ResponseOneOfAllOfRemediation{}
	return &this
}

// NewGetIssue200ResponseOneOfAllOfRemediationWithDefaults instantiates a new GetIssue200ResponseOneOfAllOfRemediation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIssue200ResponseOneOfAllOfRemediationWithDefaults() *GetIssue200ResponseOneOfAllOfRemediation {
	this := GetIssue200ResponseOneOfAllOfRemediation{}
	return &this
}

// GetPartialFix returns the PartialFix field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfRemediation) GetPartialFix() string {
	if o == nil || IsNil(o.PartialFix) {
		var ret string
		return ret
	}
	return *o.PartialFix
}

// GetPartialFixOk returns a tuple with the PartialFix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfRemediation) GetPartialFixOk() (*string, bool) {
	if o == nil || IsNil(o.PartialFix) {
		return nil, false
	}
	return o.PartialFix, true
}

// HasPartialFix returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfRemediation) HasPartialFix() bool {
	if o != nil && !IsNil(o.PartialFix) {
		return true
	}

	return false
}

// SetPartialFix gets a reference to the given string and assigns it to the PartialFix field.
func (o *GetIssue200ResponseOneOfAllOfRemediation) SetPartialFix(v string) {
	o.PartialFix = &v
}

// GetPartialFixDistance returns the PartialFixDistance field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfRemediation) GetPartialFixDistance() string {
	if o == nil || IsNil(o.PartialFixDistance) {
		var ret string
		return ret
	}
	return *o.PartialFixDistance
}

// GetPartialFixDistanceOk returns a tuple with the PartialFixDistance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfRemediation) GetPartialFixDistanceOk() (*string, bool) {
	if o == nil || IsNil(o.PartialFixDistance) {
		return nil, false
	}
	return o.PartialFixDistance, true
}

// HasPartialFixDistance returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfRemediation) HasPartialFixDistance() bool {
	if o != nil && !IsNil(o.PartialFixDistance) {
		return true
	}

	return false
}

// SetPartialFixDistance gets a reference to the given string and assigns it to the PartialFixDistance field.
func (o *GetIssue200ResponseOneOfAllOfRemediation) SetPartialFixDistance(v string) {
	o.PartialFixDistance = &v
}

// GetCompleteFix returns the CompleteFix field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfRemediation) GetCompleteFix() string {
	if o == nil || IsNil(o.CompleteFix) {
		var ret string
		return ret
	}
	return *o.CompleteFix
}

// GetCompleteFixOk returns a tuple with the CompleteFix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfRemediation) GetCompleteFixOk() (*string, bool) {
	if o == nil || IsNil(o.CompleteFix) {
		return nil, false
	}
	return o.CompleteFix, true
}

// HasCompleteFix returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfRemediation) HasCompleteFix() bool {
	if o != nil && !IsNil(o.CompleteFix) {
		return true
	}

	return false
}

// SetCompleteFix gets a reference to the given string and assigns it to the CompleteFix field.
func (o *GetIssue200ResponseOneOfAllOfRemediation) SetCompleteFix(v string) {
	o.CompleteFix = &v
}

// GetCompleteFixDistance returns the CompleteFixDistance field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfRemediation) GetCompleteFixDistance() string {
	if o == nil || IsNil(o.CompleteFixDistance) {
		var ret string
		return ret
	}
	return *o.CompleteFixDistance
}

// GetCompleteFixDistanceOk returns a tuple with the CompleteFixDistance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfRemediation) GetCompleteFixDistanceOk() (*string, bool) {
	if o == nil || IsNil(o.CompleteFixDistance) {
		return nil, false
	}
	return o.CompleteFixDistance, true
}

// HasCompleteFixDistance returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfRemediation) HasCompleteFixDistance() bool {
	if o != nil && !IsNil(o.CompleteFixDistance) {
		return true
	}

	return false
}

// SetCompleteFixDistance gets a reference to the given string and assigns it to the CompleteFixDistance field.
func (o *GetIssue200ResponseOneOfAllOfRemediation) SetCompleteFixDistance(v string) {
	o.CompleteFixDistance = &v
}

func (o GetIssue200ResponseOneOfAllOfRemediation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIssue200ResponseOneOfAllOfRemediation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PartialFix) {
		toSerialize["partialFix"] = o.PartialFix
	}
	if !IsNil(o.PartialFixDistance) {
		toSerialize["partialFixDistance"] = o.PartialFixDistance
	}
	if !IsNil(o.CompleteFix) {
		toSerialize["completeFix"] = o.CompleteFix
	}
	if !IsNil(o.CompleteFixDistance) {
		toSerialize["completeFixDistance"] = o.CompleteFixDistance
	}
	return toSerialize, nil
}

type NullableGetIssue200ResponseOneOfAllOfRemediation struct {
	value *GetIssue200ResponseOneOfAllOfRemediation
	isSet bool
}

func (v NullableGetIssue200ResponseOneOfAllOfRemediation) Get() *GetIssue200ResponseOneOfAllOfRemediation {
	return v.value
}

func (v *NullableGetIssue200ResponseOneOfAllOfRemediation) Set(val *GetIssue200ResponseOneOfAllOfRemediation) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIssue200ResponseOneOfAllOfRemediation) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIssue200ResponseOneOfAllOfRemediation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIssue200ResponseOneOfAllOfRemediation(val *GetIssue200ResponseOneOfAllOfRemediation) *NullableGetIssue200ResponseOneOfAllOfRemediation {
	return &NullableGetIssue200ResponseOneOfAllOfRemediation{value: val, isSet: true}
}

func (v NullableGetIssue200ResponseOneOfAllOfRemediation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIssue200ResponseOneOfAllOfRemediation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


