/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.66
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// CreateOIDCProviderRequest - struct for CreateOIDCProviderRequest
type CreateOIDCProviderRequest struct {
	CreateOIDCProviderRequestOneOf *CreateOIDCProviderRequestOneOf
	CreateOIDCProviderRequestOneOf1 *CreateOIDCProviderRequestOneOf1
}

// CreateOIDCProviderRequestOneOfAsCreateOIDCProviderRequest is a convenience function that returns CreateOIDCProviderRequestOneOf wrapped in CreateOIDCProviderRequest
func CreateOIDCProviderRequestOneOfAsCreateOIDCProviderRequest(v *CreateOIDCProviderRequestOneOf) CreateOIDCProviderRequest {
	return CreateOIDCProviderRequest{
		CreateOIDCProviderRequestOneOf: v,
	}
}

// CreateOIDCProviderRequestOneOf1AsCreateOIDCProviderRequest is a convenience function that returns CreateOIDCProviderRequestOneOf1 wrapped in CreateOIDCProviderRequest
func CreateOIDCProviderRequestOneOf1AsCreateOIDCProviderRequest(v *CreateOIDCProviderRequestOneOf1) CreateOIDCProviderRequest {
	return CreateOIDCProviderRequest{
		CreateOIDCProviderRequestOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *CreateOIDCProviderRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateOIDCProviderRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.CreateOIDCProviderRequestOneOf)
	if err == nil {
		jsonCreateOIDCProviderRequestOneOf, _ := json.Marshal(dst.CreateOIDCProviderRequestOneOf)
		if string(jsonCreateOIDCProviderRequestOneOf) == "{}" { // empty struct
			dst.CreateOIDCProviderRequestOneOf = nil
		} else {
			if err = validator.Validate(dst.CreateOIDCProviderRequestOneOf); err != nil {
				dst.CreateOIDCProviderRequestOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateOIDCProviderRequestOneOf = nil
	}

	// try to unmarshal data into CreateOIDCProviderRequestOneOf1
	err = newStrictDecoder(data).Decode(&dst.CreateOIDCProviderRequestOneOf1)
	if err == nil {
		jsonCreateOIDCProviderRequestOneOf1, _ := json.Marshal(dst.CreateOIDCProviderRequestOneOf1)
		if string(jsonCreateOIDCProviderRequestOneOf1) == "{}" { // empty struct
			dst.CreateOIDCProviderRequestOneOf1 = nil
		} else {
			if err = validator.Validate(dst.CreateOIDCProviderRequestOneOf1); err != nil {
				dst.CreateOIDCProviderRequestOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateOIDCProviderRequestOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateOIDCProviderRequestOneOf = nil
		dst.CreateOIDCProviderRequestOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(CreateOIDCProviderRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(CreateOIDCProviderRequest): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(CreateOIDCProviderRequest)")
        }
        if err != nil {
            return fmt.Errorf("data failed to match schemas in oneOf(CreateOIDCProviderRequest): %v", err)
        } else {
            return fmt.Errorf("data failed to match schemas in oneOf(CreateOIDCProviderRequest)")
        }
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src CreateOIDCProviderRequest) MarshalJSON() ([]byte, error) {
	if src.CreateOIDCProviderRequestOneOf != nil {
		return json.Marshal(&src.CreateOIDCProviderRequestOneOf)
	}

	if src.CreateOIDCProviderRequestOneOf1 != nil {
		return json.Marshal(&src.CreateOIDCProviderRequestOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *CreateOIDCProviderRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateOIDCProviderRequestOneOf != nil {
		return obj.CreateOIDCProviderRequestOneOf
	}

	if obj.CreateOIDCProviderRequestOneOf1 != nil {
		return obj.CreateOIDCProviderRequestOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj CreateOIDCProviderRequest) GetActualInstanceValue() (interface{}) {
	if obj.CreateOIDCProviderRequestOneOf != nil {
		return *obj.CreateOIDCProviderRequestOneOf
	}

	if obj.CreateOIDCProviderRequestOneOf1 != nil {
		return *obj.CreateOIDCProviderRequestOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableCreateOIDCProviderRequest struct {
	value *CreateOIDCProviderRequest
	isSet bool
}

func (v NullableCreateOIDCProviderRequest) Get() *CreateOIDCProviderRequest {
	return v.value
}

func (v *NullableCreateOIDCProviderRequest) Set(val *CreateOIDCProviderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOIDCProviderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOIDCProviderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOIDCProviderRequest(val *CreateOIDCProviderRequest) *NullableCreateOIDCProviderRequest {
	return &NullableCreateOIDCProviderRequest{value: val, isSet: true}
}

func (v NullableCreateOIDCProviderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOIDCProviderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


