/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.33.50
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateTeamUsersRequestUsersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTeamUsersRequestUsersInner{}

// UpdateTeamUsersRequestUsersInner struct for UpdateTeamUsersRequestUsersInner
type UpdateTeamUsersRequestUsersInner struct {
	// ID of the user
	UserId int32 `json:"userId"`
	// Role ID for the user (required for add and update actions)
	RoleId *int32 `json:"roleId,omitempty"`
}

type _UpdateTeamUsersRequestUsersInner UpdateTeamUsersRequestUsersInner

// NewUpdateTeamUsersRequestUsersInner instantiates a new UpdateTeamUsersRequestUsersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTeamUsersRequestUsersInner(userId int32) *UpdateTeamUsersRequestUsersInner {
	this := UpdateTeamUsersRequestUsersInner{}
	this.UserId = userId
	return &this
}

// NewUpdateTeamUsersRequestUsersInnerWithDefaults instantiates a new UpdateTeamUsersRequestUsersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTeamUsersRequestUsersInnerWithDefaults() *UpdateTeamUsersRequestUsersInner {
	this := UpdateTeamUsersRequestUsersInner{}
	return &this
}

// GetUserId returns the UserId field value
func (o *UpdateTeamUsersRequestUsersInner) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UpdateTeamUsersRequestUsersInner) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UpdateTeamUsersRequestUsersInner) SetUserId(v int32) {
	o.UserId = v
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *UpdateTeamUsersRequestUsersInner) GetRoleId() int32 {
	if o == nil || IsNil(o.RoleId) {
		var ret int32
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTeamUsersRequestUsersInner) GetRoleIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *UpdateTeamUsersRequestUsersInner) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given int32 and assigns it to the RoleId field.
func (o *UpdateTeamUsersRequestUsersInner) SetRoleId(v int32) {
	o.RoleId = &v
}

func (o UpdateTeamUsersRequestUsersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTeamUsersRequestUsersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	if !IsNil(o.RoleId) {
		toSerialize["roleId"] = o.RoleId
	}
	return toSerialize, nil
}

func (o *UpdateTeamUsersRequestUsersInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTeamUsersRequestUsersInner := _UpdateTeamUsersRequestUsersInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTeamUsersRequestUsersInner)

	if err != nil {
		return err
	}

	*o = UpdateTeamUsersRequestUsersInner(varUpdateTeamUsersRequestUsersInner)

	return err
}

type NullableUpdateTeamUsersRequestUsersInner struct {
	value *UpdateTeamUsersRequestUsersInner
	isSet bool
}

func (v NullableUpdateTeamUsersRequestUsersInner) Get() *UpdateTeamUsersRequestUsersInner {
	return v.value
}

func (v *NullableUpdateTeamUsersRequestUsersInner) Set(val *UpdateTeamUsersRequestUsersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTeamUsersRequestUsersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTeamUsersRequestUsersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTeamUsersRequestUsersInner(val *UpdateTeamUsersRequestUsersInner) *NullableUpdateTeamUsersRequestUsersInner {
	return &NullableUpdateTeamUsersRequestUsersInner{value: val, isSet: true}
}

func (v NullableUpdateTeamUsersRequestUsersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTeamUsersRequestUsersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


