/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.76
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOIDCProviderRequestOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOIDCProviderRequestOneOf1{}

// CreateOIDCProviderRequestOneOf1 struct for CreateOIDCProviderRequestOneOf1
type CreateOIDCProviderRequestOneOf1 struct {
	// The issuer URL of the OIDC Provider
	Issuer string `json:"issuer"`
	// The scope level of the OIDC Provider
	Scope string `json:"scope"`
}

type _CreateOIDCProviderRequestOneOf1 CreateOIDCProviderRequestOneOf1

// NewCreateOIDCProviderRequestOneOf1 instantiates a new CreateOIDCProviderRequestOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOIDCProviderRequestOneOf1(issuer string, scope string) *CreateOIDCProviderRequestOneOf1 {
	this := CreateOIDCProviderRequestOneOf1{}
	this.Issuer = issuer
	this.Scope = scope
	return &this
}

// NewCreateOIDCProviderRequestOneOf1WithDefaults instantiates a new CreateOIDCProviderRequestOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOIDCProviderRequestOneOf1WithDefaults() *CreateOIDCProviderRequestOneOf1 {
	this := CreateOIDCProviderRequestOneOf1{}
	return &this
}

// GetIssuer returns the Issuer field value
func (o *CreateOIDCProviderRequestOneOf1) GetIssuer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCProviderRequestOneOf1) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issuer, true
}

// SetIssuer sets field value
func (o *CreateOIDCProviderRequestOneOf1) SetIssuer(v string) {
	o.Issuer = v
}

// GetScope returns the Scope field value
func (o *CreateOIDCProviderRequestOneOf1) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCProviderRequestOneOf1) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *CreateOIDCProviderRequestOneOf1) SetScope(v string) {
	o.Scope = v
}

func (o CreateOIDCProviderRequestOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOIDCProviderRequestOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["issuer"] = o.Issuer
	toSerialize["scope"] = o.Scope
	return toSerialize, nil
}

func (o *CreateOIDCProviderRequestOneOf1) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"issuer",
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOIDCProviderRequestOneOf1 := _CreateOIDCProviderRequestOneOf1{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOIDCProviderRequestOneOf1)

	if err != nil {
		return err
	}

	*o = CreateOIDCProviderRequestOneOf1(varCreateOIDCProviderRequestOneOf1)

	return err
}

type NullableCreateOIDCProviderRequestOneOf1 struct {
	value *CreateOIDCProviderRequestOneOf1
	isSet bool
}

func (v NullableCreateOIDCProviderRequestOneOf1) Get() *CreateOIDCProviderRequestOneOf1 {
	return v.value
}

func (v *NullableCreateOIDCProviderRequestOneOf1) Set(val *CreateOIDCProviderRequestOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOIDCProviderRequestOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOIDCProviderRequestOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOIDCProviderRequestOneOf1(val *CreateOIDCProviderRequestOneOf1) *NullableCreateOIDCProviderRequestOneOf1 {
	return &NullableCreateOIDCProviderRequestOneOf1{value: val, isSet: true}
}

func (v NullableCreateOIDCProviderRequestOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOIDCProviderRequestOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


