/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.30.21
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetSnippetById200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSnippetById200Response{}

// GetSnippetById200Response struct for GetSnippetById200Response
type GetSnippetById200Response struct {
	Snippet GetSnippets200ResponseResultsInner `json:"snippet"`
}

type _GetSnippetById200Response GetSnippetById200Response

// NewGetSnippetById200Response instantiates a new GetSnippetById200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSnippetById200Response(snippet GetSnippets200ResponseResultsInner) *GetSnippetById200Response {
	this := GetSnippetById200Response{}
	this.Snippet = snippet
	return &this
}

// NewGetSnippetById200ResponseWithDefaults instantiates a new GetSnippetById200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSnippetById200ResponseWithDefaults() *GetSnippetById200Response {
	this := GetSnippetById200Response{}
	return &this
}

// GetSnippet returns the Snippet field value
func (o *GetSnippetById200Response) GetSnippet() GetSnippets200ResponseResultsInner {
	if o == nil {
		var ret GetSnippets200ResponseResultsInner
		return ret
	}

	return o.Snippet
}

// GetSnippetOk returns a tuple with the Snippet field value
// and a boolean to check if the value has been set.
func (o *GetSnippetById200Response) GetSnippetOk() (*GetSnippets200ResponseResultsInner, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Snippet, true
}

// SetSnippet sets field value
func (o *GetSnippetById200Response) SetSnippet(v GetSnippets200ResponseResultsInner) {
	o.Snippet = v
}

func (o GetSnippetById200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSnippetById200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["snippet"] = o.Snippet
	return toSerialize, nil
}

func (o *GetSnippetById200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"snippet",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetSnippetById200Response := _GetSnippetById200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetSnippetById200Response)

	if err != nil {
		return err
	}

	*o = GetSnippetById200Response(varGetSnippetById200Response)

	return err
}

type NullableGetSnippetById200Response struct {
	value *GetSnippetById200Response
	isSet bool
}

func (v NullableGetSnippetById200Response) Get() *GetSnippetById200Response {
	return v.value
}

func (v *NullableGetSnippetById200Response) Set(val *GetSnippetById200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSnippetById200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSnippetById200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSnippetById200Response(val *GetSnippetById200Response) *NullableGetSnippetById200Response {
	return &NullableGetSnippetById200Response{value: val, isSet: true}
}

func (v NullableGetSnippetById200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSnippetById200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


