/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.33.24
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UserInvitation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserInvitation{}

// UserInvitation struct for UserInvitation
type UserInvitation struct {
	OrganizationId int32 `json:"organizationId"`
	Email string `json:"email"`
	TokenId int32 `json:"tokenId"`
	CreatedByUserId int32 `json:"createdByUserId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Token UserInvitationToken `json:"token"`
}

type _UserInvitation UserInvitation

// NewUserInvitation instantiates a new UserInvitation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserInvitation(organizationId int32, email string, tokenId int32, createdByUserId int32, createdAt time.Time, updatedAt time.Time, token UserInvitationToken) *UserInvitation {
	this := UserInvitation{}
	this.OrganizationId = organizationId
	this.Email = email
	this.TokenId = tokenId
	this.CreatedByUserId = createdByUserId
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Token = token
	return &this
}

// NewUserInvitationWithDefaults instantiates a new UserInvitation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserInvitationWithDefaults() *UserInvitation {
	this := UserInvitation{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *UserInvitation) GetOrganizationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *UserInvitation) GetOrganizationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *UserInvitation) SetOrganizationId(v int32) {
	o.OrganizationId = v
}

// GetEmail returns the Email field value
func (o *UserInvitation) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserInvitation) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserInvitation) SetEmail(v string) {
	o.Email = v
}

// GetTokenId returns the TokenId field value
func (o *UserInvitation) GetTokenId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *UserInvitation) GetTokenIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *UserInvitation) SetTokenId(v int32) {
	o.TokenId = v
}

// GetCreatedByUserId returns the CreatedByUserId field value
func (o *UserInvitation) GetCreatedByUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CreatedByUserId
}

// GetCreatedByUserIdOk returns a tuple with the CreatedByUserId field value
// and a boolean to check if the value has been set.
func (o *UserInvitation) GetCreatedByUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedByUserId, true
}

// SetCreatedByUserId sets field value
func (o *UserInvitation) SetCreatedByUserId(v int32) {
	o.CreatedByUserId = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UserInvitation) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UserInvitation) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UserInvitation) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UserInvitation) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UserInvitation) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UserInvitation) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetToken returns the Token field value
func (o *UserInvitation) GetToken() UserInvitationToken {
	if o == nil {
		var ret UserInvitationToken
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *UserInvitation) GetTokenOk() (*UserInvitationToken, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *UserInvitation) SetToken(v UserInvitationToken) {
	o.Token = v
}

func (o UserInvitation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserInvitation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["email"] = o.Email
	toSerialize["tokenId"] = o.TokenId
	toSerialize["createdByUserId"] = o.CreatedByUserId
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["token"] = o.Token
	return toSerialize, nil
}

func (o *UserInvitation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organizationId",
		"email",
		"tokenId",
		"createdByUserId",
		"createdAt",
		"updatedAt",
		"token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserInvitation := _UserInvitation{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserInvitation)

	if err != nil {
		return err
	}

	*o = UserInvitation(varUserInvitation)

	return err
}

type NullableUserInvitation struct {
	value *UserInvitation
	isSet bool
}

func (v NullableUserInvitation) Get() *UserInvitation {
	return v.value
}

func (v *NullableUserInvitation) Set(val *UserInvitation) {
	v.value = val
	v.isSet = true
}

func (v NullableUserInvitation) IsSet() bool {
	return v.isSet
}

func (v *NullableUserInvitation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserInvitation(val *UserInvitation) *NullableUserInvitation {
	return &NullableUserInvitation{value: val, isSet: true}
}

func (v NullableUserInvitation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserInvitation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


