/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.30.21
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOIDCTrustRelationshipRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOIDCTrustRelationshipRequest{}

// CreateOIDCTrustRelationshipRequest struct for CreateOIDCTrustRelationshipRequest
type CreateOIDCTrustRelationshipRequest struct {
	// The ID of the user to associate with this trust relationship
	UserId int32 `json:"userId"`
	// The ID of the OIDC Provider to use for this trust relationship
	ProviderId int32 `json:"providerId"`
	// Array of valid audiences for this trust relationship (max 5)
	Audiences []string `json:"audiences"`
	// Array of claim objects. Must contain at least one object with claim: \"sub\". Additional objects with other claims are optional. 
	RequiredClaims []CreateOIDCTrustRelationshipRequestRequiredClaimsInner `json:"requiredClaims"`
}

type _CreateOIDCTrustRelationshipRequest CreateOIDCTrustRelationshipRequest

// NewCreateOIDCTrustRelationshipRequest instantiates a new CreateOIDCTrustRelationshipRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOIDCTrustRelationshipRequest(userId int32, providerId int32, audiences []string, requiredClaims []CreateOIDCTrustRelationshipRequestRequiredClaimsInner) *CreateOIDCTrustRelationshipRequest {
	this := CreateOIDCTrustRelationshipRequest{}
	this.UserId = userId
	this.ProviderId = providerId
	this.Audiences = audiences
	this.RequiredClaims = requiredClaims
	return &this
}

// NewCreateOIDCTrustRelationshipRequestWithDefaults instantiates a new CreateOIDCTrustRelationshipRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOIDCTrustRelationshipRequestWithDefaults() *CreateOIDCTrustRelationshipRequest {
	this := CreateOIDCTrustRelationshipRequest{}
	return &this
}

// GetUserId returns the UserId field value
func (o *CreateOIDCTrustRelationshipRequest) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationshipRequest) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CreateOIDCTrustRelationshipRequest) SetUserId(v int32) {
	o.UserId = v
}

// GetProviderId returns the ProviderId field value
func (o *CreateOIDCTrustRelationshipRequest) GetProviderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationshipRequest) GetProviderIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *CreateOIDCTrustRelationshipRequest) SetProviderId(v int32) {
	o.ProviderId = v
}

// GetAudiences returns the Audiences field value
func (o *CreateOIDCTrustRelationshipRequest) GetAudiences() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationshipRequest) GetAudiencesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Audiences, true
}

// SetAudiences sets field value
func (o *CreateOIDCTrustRelationshipRequest) SetAudiences(v []string) {
	o.Audiences = v
}

// GetRequiredClaims returns the RequiredClaims field value
func (o *CreateOIDCTrustRelationshipRequest) GetRequiredClaims() []CreateOIDCTrustRelationshipRequestRequiredClaimsInner {
	if o == nil {
		var ret []CreateOIDCTrustRelationshipRequestRequiredClaimsInner
		return ret
	}

	return o.RequiredClaims
}

// GetRequiredClaimsOk returns a tuple with the RequiredClaims field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationshipRequest) GetRequiredClaimsOk() ([]CreateOIDCTrustRelationshipRequestRequiredClaimsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredClaims, true
}

// SetRequiredClaims sets field value
func (o *CreateOIDCTrustRelationshipRequest) SetRequiredClaims(v []CreateOIDCTrustRelationshipRequestRequiredClaimsInner) {
	o.RequiredClaims = v
}

func (o CreateOIDCTrustRelationshipRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOIDCTrustRelationshipRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["providerId"] = o.ProviderId
	toSerialize["audiences"] = o.Audiences
	toSerialize["requiredClaims"] = o.RequiredClaims
	return toSerialize, nil
}

func (o *CreateOIDCTrustRelationshipRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
		"providerId",
		"audiences",
		"requiredClaims",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOIDCTrustRelationshipRequest := _CreateOIDCTrustRelationshipRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOIDCTrustRelationshipRequest)

	if err != nil {
		return err
	}

	*o = CreateOIDCTrustRelationshipRequest(varCreateOIDCTrustRelationshipRequest)

	return err
}

type NullableCreateOIDCTrustRelationshipRequest struct {
	value *CreateOIDCTrustRelationshipRequest
	isSet bool
}

func (v NullableCreateOIDCTrustRelationshipRequest) Get() *CreateOIDCTrustRelationshipRequest {
	return v.value
}

func (v *NullableCreateOIDCTrustRelationshipRequest) Set(val *CreateOIDCTrustRelationshipRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOIDCTrustRelationshipRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOIDCTrustRelationshipRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOIDCTrustRelationshipRequest(val *CreateOIDCTrustRelationshipRequest) *NullableCreateOIDCTrustRelationshipRequest {
	return &NullableCreateOIDCTrustRelationshipRequest{value: val, isSet: true}
}

func (v NullableCreateOIDCTrustRelationshipRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOIDCTrustRelationshipRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


