/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.33.64
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the GetRevisionDependenciesPost404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRevisionDependenciesPost404Response{}

// GetRevisionDependenciesPost404Response struct for GetRevisionDependenciesPost404Response
type GetRevisionDependenciesPost404Response struct {
	Error *string `json:"error,omitempty"`
}

// NewGetRevisionDependenciesPost404Response instantiates a new GetRevisionDependenciesPost404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRevisionDependenciesPost404Response() *GetRevisionDependenciesPost404Response {
	this := GetRevisionDependenciesPost404Response{}
	return &this
}

// NewGetRevisionDependenciesPost404ResponseWithDefaults instantiates a new GetRevisionDependenciesPost404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRevisionDependenciesPost404ResponseWithDefaults() *GetRevisionDependenciesPost404Response {
	this := GetRevisionDependenciesPost404Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetRevisionDependenciesPost404Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevisionDependenciesPost404Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetRevisionDependenciesPost404Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetRevisionDependenciesPost404Response) SetError(v string) {
	o.Error = &v
}

func (o GetRevisionDependenciesPost404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRevisionDependenciesPost404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableGetRevisionDependenciesPost404Response struct {
	value *GetRevisionDependenciesPost404Response
	isSet bool
}

func (v NullableGetRevisionDependenciesPost404Response) Get() *GetRevisionDependenciesPost404Response {
	return v.value
}

func (v *NullableGetRevisionDependenciesPost404Response) Set(val *GetRevisionDependenciesPost404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRevisionDependenciesPost404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRevisionDependenciesPost404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRevisionDependenciesPost404Response(val *GetRevisionDependenciesPost404Response) *NullableGetRevisionDependenciesPost404Response {
	return &NullableGetRevisionDependenciesPost404Response{value: val, isSet: true}
}

func (v NullableGetRevisionDependenciesPost404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRevisionDependenciesPost404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


