/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.28.61
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the GetIssue200ResponseOneOfAllOfSource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIssue200ResponseOneOfAllOfSource{}

// GetIssue200ResponseOneOfAllOfSource struct for GetIssue200ResponseOneOfAllOfSource
type GetIssue200ResponseOneOfAllOfSource struct {
	Id *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Url *string `json:"url,omitempty"`
	Version *string `json:"version,omitempty"`
	PackageManager *string `json:"packageManager,omitempty"`
}

// NewGetIssue200ResponseOneOfAllOfSource instantiates a new GetIssue200ResponseOneOfAllOfSource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIssue200ResponseOneOfAllOfSource() *GetIssue200ResponseOneOfAllOfSource {
	this := GetIssue200ResponseOneOfAllOfSource{}
	return &this
}

// NewGetIssue200ResponseOneOfAllOfSourceWithDefaults instantiates a new GetIssue200ResponseOneOfAllOfSource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIssue200ResponseOneOfAllOfSourceWithDefaults() *GetIssue200ResponseOneOfAllOfSource {
	this := GetIssue200ResponseOneOfAllOfSource{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfSource) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetIssue200ResponseOneOfAllOfSource) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfSource) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetIssue200ResponseOneOfAllOfSource) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfSource) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GetIssue200ResponseOneOfAllOfSource) SetUrl(v string) {
	o.Url = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfSource) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *GetIssue200ResponseOneOfAllOfSource) SetVersion(v string) {
	o.Version = &v
}

// GetPackageManager returns the PackageManager field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfSource) GetPackageManager() string {
	if o == nil || IsNil(o.PackageManager) {
		var ret string
		return ret
	}
	return *o.PackageManager
}

// GetPackageManagerOk returns a tuple with the PackageManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) GetPackageManagerOk() (*string, bool) {
	if o == nil || IsNil(o.PackageManager) {
		return nil, false
	}
	return o.PackageManager, true
}

// HasPackageManager returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfSource) HasPackageManager() bool {
	if o != nil && !IsNil(o.PackageManager) {
		return true
	}

	return false
}

// SetPackageManager gets a reference to the given string and assigns it to the PackageManager field.
func (o *GetIssue200ResponseOneOfAllOfSource) SetPackageManager(v string) {
	o.PackageManager = &v
}

func (o GetIssue200ResponseOneOfAllOfSource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIssue200ResponseOneOfAllOfSource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	if !IsNil(o.PackageManager) {
		toSerialize["packageManager"] = o.PackageManager
	}
	return toSerialize, nil
}

type NullableGetIssue200ResponseOneOfAllOfSource struct {
	value *GetIssue200ResponseOneOfAllOfSource
	isSet bool
}

func (v NullableGetIssue200ResponseOneOfAllOfSource) Get() *GetIssue200ResponseOneOfAllOfSource {
	return v.value
}

func (v *NullableGetIssue200ResponseOneOfAllOfSource) Set(val *GetIssue200ResponseOneOfAllOfSource) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIssue200ResponseOneOfAllOfSource) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIssue200ResponseOneOfAllOfSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIssue200ResponseOneOfAllOfSource(val *GetIssue200ResponseOneOfAllOfSource) *NullableGetIssue200ResponseOneOfAllOfSource {
	return &NullableGetIssue200ResponseOneOfAllOfSource{value: val, isSet: true}
}

func (v NullableGetIssue200ResponseOneOfAllOfSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIssue200ResponseOneOfAllOfSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


