/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.32.23
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the GetProjectDependency200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectDependency200Response{}

// GetProjectDependency200Response struct for GetProjectDependency200Response
type GetProjectDependency200Response struct {
	Dependency *GetProjectDependencies200ResponseDependenciesInner `json:"dependency,omitempty"`
}

// NewGetProjectDependency200Response instantiates a new GetProjectDependency200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectDependency200Response() *GetProjectDependency200Response {
	this := GetProjectDependency200Response{}
	return &this
}

// NewGetProjectDependency200ResponseWithDefaults instantiates a new GetProjectDependency200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectDependency200ResponseWithDefaults() *GetProjectDependency200Response {
	this := GetProjectDependency200Response{}
	return &this
}

// GetDependency returns the Dependency field value if set, zero value otherwise.
func (o *GetProjectDependency200Response) GetDependency() GetProjectDependencies200ResponseDependenciesInner {
	if o == nil || IsNil(o.Dependency) {
		var ret GetProjectDependencies200ResponseDependenciesInner
		return ret
	}
	return *o.Dependency
}

// GetDependencyOk returns a tuple with the Dependency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectDependency200Response) GetDependencyOk() (*GetProjectDependencies200ResponseDependenciesInner, bool) {
	if o == nil || IsNil(o.Dependency) {
		return nil, false
	}
	return o.Dependency, true
}

// HasDependency returns a boolean if a field has been set.
func (o *GetProjectDependency200Response) HasDependency() bool {
	if o != nil && !IsNil(o.Dependency) {
		return true
	}

	return false
}

// SetDependency gets a reference to the given GetProjectDependencies200ResponseDependenciesInner and assigns it to the Dependency field.
func (o *GetProjectDependency200Response) SetDependency(v GetProjectDependencies200ResponseDependenciesInner) {
	o.Dependency = &v
}

func (o GetProjectDependency200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectDependency200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Dependency) {
		toSerialize["dependency"] = o.Dependency
	}
	return toSerialize, nil
}

type NullableGetProjectDependency200Response struct {
	value *GetProjectDependency200Response
	isSet bool
}

func (v NullableGetProjectDependency200Response) Get() *GetProjectDependency200Response {
	return v.value
}

func (v *NullableGetProjectDependency200Response) Set(val *GetProjectDependency200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectDependency200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectDependency200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectDependency200Response(val *GetProjectDependency200Response) *NullableGetProjectDependency200Response {
	return &NullableGetProjectDependency200Response{value: val, isSet: true}
}

func (v NullableGetProjectDependency200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectDependency200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


