/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.33.42
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOIDCTrustRelationshipRequestOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOIDCTrustRelationshipRequestOneOf{}

// CreateOIDCTrustRelationshipRequestOneOf struct for CreateOIDCTrustRelationshipRequestOneOf
type CreateOIDCTrustRelationshipRequestOneOf struct {
	// The ID of the user to associate with this trust relationship
	UserId int32 `json:"userId"`
	// The ID of the OIDC Provider to use for this trust relationship
	ProviderId int32 `json:"providerId"`
	// The scope level of the trust relationship
	Scope string `json:"scope"`
	// Array of valid audiences for this trust relationship
	Audiences []string `json:"audiences"`
	// Array of claim objects. Must contain at least one object with claim: \"sub\". Additional objects with other claims are optional. 
	RequiredClaims []CreateOIDCTrustRelationshipRequestOneOfRequiredClaimsInner `json:"requiredClaims"`
}

type _CreateOIDCTrustRelationshipRequestOneOf CreateOIDCTrustRelationshipRequestOneOf

// NewCreateOIDCTrustRelationshipRequestOneOf instantiates a new CreateOIDCTrustRelationshipRequestOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOIDCTrustRelationshipRequestOneOf(userId int32, providerId int32, scope string, audiences []string, requiredClaims []CreateOIDCTrustRelationshipRequestOneOfRequiredClaimsInner) *CreateOIDCTrustRelationshipRequestOneOf {
	this := CreateOIDCTrustRelationshipRequestOneOf{}
	this.UserId = userId
	this.ProviderId = providerId
	this.Scope = scope
	this.Audiences = audiences
	this.RequiredClaims = requiredClaims
	return &this
}

// NewCreateOIDCTrustRelationshipRequestOneOfWithDefaults instantiates a new CreateOIDCTrustRelationshipRequestOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOIDCTrustRelationshipRequestOneOfWithDefaults() *CreateOIDCTrustRelationshipRequestOneOf {
	this := CreateOIDCTrustRelationshipRequestOneOf{}
	return &this
}

// GetUserId returns the UserId field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) SetUserId(v int32) {
	o.UserId = v
}

// GetProviderId returns the ProviderId field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetProviderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetProviderIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) SetProviderId(v int32) {
	o.ProviderId = v
}

// GetScope returns the Scope field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) SetScope(v string) {
	o.Scope = v
}

// GetAudiences returns the Audiences field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetAudiences() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetAudiencesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Audiences, true
}

// SetAudiences sets field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) SetAudiences(v []string) {
	o.Audiences = v
}

// GetRequiredClaims returns the RequiredClaims field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetRequiredClaims() []CreateOIDCTrustRelationshipRequestOneOfRequiredClaimsInner {
	if o == nil {
		var ret []CreateOIDCTrustRelationshipRequestOneOfRequiredClaimsInner
		return ret
	}

	return o.RequiredClaims
}

// GetRequiredClaimsOk returns a tuple with the RequiredClaims field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationshipRequestOneOf) GetRequiredClaimsOk() ([]CreateOIDCTrustRelationshipRequestOneOfRequiredClaimsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredClaims, true
}

// SetRequiredClaims sets field value
func (o *CreateOIDCTrustRelationshipRequestOneOf) SetRequiredClaims(v []CreateOIDCTrustRelationshipRequestOneOfRequiredClaimsInner) {
	o.RequiredClaims = v
}

func (o CreateOIDCTrustRelationshipRequestOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOIDCTrustRelationshipRequestOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["userId"] = o.UserId
	toSerialize["providerId"] = o.ProviderId
	toSerialize["scope"] = o.Scope
	toSerialize["audiences"] = o.Audiences
	toSerialize["requiredClaims"] = o.RequiredClaims
	return toSerialize, nil
}

func (o *CreateOIDCTrustRelationshipRequestOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
		"providerId",
		"scope",
		"audiences",
		"requiredClaims",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOIDCTrustRelationshipRequestOneOf := _CreateOIDCTrustRelationshipRequestOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOIDCTrustRelationshipRequestOneOf)

	if err != nil {
		return err
	}

	*o = CreateOIDCTrustRelationshipRequestOneOf(varCreateOIDCTrustRelationshipRequestOneOf)

	return err
}

type NullableCreateOIDCTrustRelationshipRequestOneOf struct {
	value *CreateOIDCTrustRelationshipRequestOneOf
	isSet bool
}

func (v NullableCreateOIDCTrustRelationshipRequestOneOf) Get() *CreateOIDCTrustRelationshipRequestOneOf {
	return v.value
}

func (v *NullableCreateOIDCTrustRelationshipRequestOneOf) Set(val *CreateOIDCTrustRelationshipRequestOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOIDCTrustRelationshipRequestOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOIDCTrustRelationshipRequestOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOIDCTrustRelationshipRequestOneOf(val *CreateOIDCTrustRelationshipRequestOneOf) *NullableCreateOIDCTrustRelationshipRequestOneOf {
	return &NullableCreateOIDCTrustRelationshipRequestOneOf{value: val, isSet: true}
}

func (v NullableCreateOIDCTrustRelationshipRequestOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOIDCTrustRelationshipRequestOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


