/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.28.61
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the GetPackageLabelAssignments200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPackageLabelAssignments200Response{}

// GetPackageLabelAssignments200Response struct for GetPackageLabelAssignments200Response
type GetPackageLabelAssignments200Response struct {
	PackageLabelAssignmentResponse *GetPackageLabelAssignments200ResponsePackageLabelAssignmentResponse `json:"packageLabelAssignmentResponse,omitempty"`
}

// NewGetPackageLabelAssignments200Response instantiates a new GetPackageLabelAssignments200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPackageLabelAssignments200Response() *GetPackageLabelAssignments200Response {
	this := GetPackageLabelAssignments200Response{}
	return &this
}

// NewGetPackageLabelAssignments200ResponseWithDefaults instantiates a new GetPackageLabelAssignments200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPackageLabelAssignments200ResponseWithDefaults() *GetPackageLabelAssignments200Response {
	this := GetPackageLabelAssignments200Response{}
	return &this
}

// GetPackageLabelAssignmentResponse returns the PackageLabelAssignmentResponse field value if set, zero value otherwise.
func (o *GetPackageLabelAssignments200Response) GetPackageLabelAssignmentResponse() GetPackageLabelAssignments200ResponsePackageLabelAssignmentResponse {
	if o == nil || IsNil(o.PackageLabelAssignmentResponse) {
		var ret GetPackageLabelAssignments200ResponsePackageLabelAssignmentResponse
		return ret
	}
	return *o.PackageLabelAssignmentResponse
}

// GetPackageLabelAssignmentResponseOk returns a tuple with the PackageLabelAssignmentResponse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPackageLabelAssignments200Response) GetPackageLabelAssignmentResponseOk() (*GetPackageLabelAssignments200ResponsePackageLabelAssignmentResponse, bool) {
	if o == nil || IsNil(o.PackageLabelAssignmentResponse) {
		return nil, false
	}
	return o.PackageLabelAssignmentResponse, true
}

// HasPackageLabelAssignmentResponse returns a boolean if a field has been set.
func (o *GetPackageLabelAssignments200Response) HasPackageLabelAssignmentResponse() bool {
	if o != nil && !IsNil(o.PackageLabelAssignmentResponse) {
		return true
	}

	return false
}

// SetPackageLabelAssignmentResponse gets a reference to the given GetPackageLabelAssignments200ResponsePackageLabelAssignmentResponse and assigns it to the PackageLabelAssignmentResponse field.
func (o *GetPackageLabelAssignments200Response) SetPackageLabelAssignmentResponse(v GetPackageLabelAssignments200ResponsePackageLabelAssignmentResponse) {
	o.PackageLabelAssignmentResponse = &v
}

func (o GetPackageLabelAssignments200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPackageLabelAssignments200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PackageLabelAssignmentResponse) {
		toSerialize["packageLabelAssignmentResponse"] = o.PackageLabelAssignmentResponse
	}
	return toSerialize, nil
}

type NullableGetPackageLabelAssignments200Response struct {
	value *GetPackageLabelAssignments200Response
	isSet bool
}

func (v NullableGetPackageLabelAssignments200Response) Get() *GetPackageLabelAssignments200Response {
	return v.value
}

func (v *NullableGetPackageLabelAssignments200Response) Set(val *GetPackageLabelAssignments200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPackageLabelAssignments200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPackageLabelAssignments200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPackageLabelAssignments200Response(val *GetPackageLabelAssignments200Response) *NullableGetPackageLabelAssignments200Response {
	return &NullableGetPackageLabelAssignments200Response{value: val, isSet: true}
}

func (v NullableGetPackageLabelAssignments200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPackageLabelAssignments200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


