/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.28.61
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the GetIssue200ResponseOneOfAllOfMetricsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIssue200ResponseOneOfAllOfMetricsInner{}

// GetIssue200ResponseOneOfAllOfMetricsInner struct for GetIssue200ResponseOneOfAllOfMetricsInner
type GetIssue200ResponseOneOfAllOfMetricsInner struct {
	Name *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewGetIssue200ResponseOneOfAllOfMetricsInner instantiates a new GetIssue200ResponseOneOfAllOfMetricsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIssue200ResponseOneOfAllOfMetricsInner() *GetIssue200ResponseOneOfAllOfMetricsInner {
	this := GetIssue200ResponseOneOfAllOfMetricsInner{}
	return &this
}

// NewGetIssue200ResponseOneOfAllOfMetricsInnerWithDefaults instantiates a new GetIssue200ResponseOneOfAllOfMetricsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIssue200ResponseOneOfAllOfMetricsInnerWithDefaults() *GetIssue200ResponseOneOfAllOfMetricsInner {
	this := GetIssue200ResponseOneOfAllOfMetricsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfMetricsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfMetricsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfMetricsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetIssue200ResponseOneOfAllOfMetricsInner) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *GetIssue200ResponseOneOfAllOfMetricsInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIssue200ResponseOneOfAllOfMetricsInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *GetIssue200ResponseOneOfAllOfMetricsInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *GetIssue200ResponseOneOfAllOfMetricsInner) SetValue(v string) {
	o.Value = &v
}

func (o GetIssue200ResponseOneOfAllOfMetricsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIssue200ResponseOneOfAllOfMetricsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableGetIssue200ResponseOneOfAllOfMetricsInner struct {
	value *GetIssue200ResponseOneOfAllOfMetricsInner
	isSet bool
}

func (v NullableGetIssue200ResponseOneOfAllOfMetricsInner) Get() *GetIssue200ResponseOneOfAllOfMetricsInner {
	return v.value
}

func (v *NullableGetIssue200ResponseOneOfAllOfMetricsInner) Set(val *GetIssue200ResponseOneOfAllOfMetricsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIssue200ResponseOneOfAllOfMetricsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIssue200ResponseOneOfAllOfMetricsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIssue200ResponseOneOfAllOfMetricsInner(val *GetIssue200ResponseOneOfAllOfMetricsInner) *NullableGetIssue200ResponseOneOfAllOfMetricsInner {
	return &NullableGetIssue200ResponseOneOfAllOfMetricsInner{value: val, isSet: true}
}

func (v NullableGetIssue200ResponseOneOfAllOfMetricsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIssue200ResponseOneOfAllOfMetricsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


