/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.28.61
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the EditingGeneralOrganizationSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditingGeneralOrganizationSettings{}

// EditingGeneralOrganizationSettings struct for EditingGeneralOrganizationSettings
type EditingGeneralOrganizationSettings struct {
	Labels []string `json:"labels,omitempty"`
	Title *string `json:"title,omitempty"`
	Email *string `json:"email,omitempty"`
	DefaultRoleId *int32 `json:"defaultRoleId,omitempty"`
	DependencySignatures *string `json:"dependencySignatures,omitempty"`
	DisableNonCustomTeamUserRoles *bool `json:"disableNonCustomTeamUserRoles,omitempty"`
}

// NewEditingGeneralOrganizationSettings instantiates a new EditingGeneralOrganizationSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditingGeneralOrganizationSettings() *EditingGeneralOrganizationSettings {
	this := EditingGeneralOrganizationSettings{}
	return &this
}

// NewEditingGeneralOrganizationSettingsWithDefaults instantiates a new EditingGeneralOrganizationSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditingGeneralOrganizationSettingsWithDefaults() *EditingGeneralOrganizationSettings {
	this := EditingGeneralOrganizationSettings{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *EditingGeneralOrganizationSettings) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditingGeneralOrganizationSettings) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *EditingGeneralOrganizationSettings) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *EditingGeneralOrganizationSettings) SetLabels(v []string) {
	o.Labels = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *EditingGeneralOrganizationSettings) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditingGeneralOrganizationSettings) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *EditingGeneralOrganizationSettings) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *EditingGeneralOrganizationSettings) SetTitle(v string) {
	o.Title = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *EditingGeneralOrganizationSettings) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditingGeneralOrganizationSettings) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *EditingGeneralOrganizationSettings) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *EditingGeneralOrganizationSettings) SetEmail(v string) {
	o.Email = &v
}

// GetDefaultRoleId returns the DefaultRoleId field value if set, zero value otherwise.
func (o *EditingGeneralOrganizationSettings) GetDefaultRoleId() int32 {
	if o == nil || IsNil(o.DefaultRoleId) {
		var ret int32
		return ret
	}
	return *o.DefaultRoleId
}

// GetDefaultRoleIdOk returns a tuple with the DefaultRoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditingGeneralOrganizationSettings) GetDefaultRoleIdOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultRoleId) {
		return nil, false
	}
	return o.DefaultRoleId, true
}

// HasDefaultRoleId returns a boolean if a field has been set.
func (o *EditingGeneralOrganizationSettings) HasDefaultRoleId() bool {
	if o != nil && !IsNil(o.DefaultRoleId) {
		return true
	}

	return false
}

// SetDefaultRoleId gets a reference to the given int32 and assigns it to the DefaultRoleId field.
func (o *EditingGeneralOrganizationSettings) SetDefaultRoleId(v int32) {
	o.DefaultRoleId = &v
}

// GetDependencySignatures returns the DependencySignatures field value if set, zero value otherwise.
func (o *EditingGeneralOrganizationSettings) GetDependencySignatures() string {
	if o == nil || IsNil(o.DependencySignatures) {
		var ret string
		return ret
	}
	return *o.DependencySignatures
}

// GetDependencySignaturesOk returns a tuple with the DependencySignatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditingGeneralOrganizationSettings) GetDependencySignaturesOk() (*string, bool) {
	if o == nil || IsNil(o.DependencySignatures) {
		return nil, false
	}
	return o.DependencySignatures, true
}

// HasDependencySignatures returns a boolean if a field has been set.
func (o *EditingGeneralOrganizationSettings) HasDependencySignatures() bool {
	if o != nil && !IsNil(o.DependencySignatures) {
		return true
	}

	return false
}

// SetDependencySignatures gets a reference to the given string and assigns it to the DependencySignatures field.
func (o *EditingGeneralOrganizationSettings) SetDependencySignatures(v string) {
	o.DependencySignatures = &v
}

// GetDisableNonCustomTeamUserRoles returns the DisableNonCustomTeamUserRoles field value if set, zero value otherwise.
func (o *EditingGeneralOrganizationSettings) GetDisableNonCustomTeamUserRoles() bool {
	if o == nil || IsNil(o.DisableNonCustomTeamUserRoles) {
		var ret bool
		return ret
	}
	return *o.DisableNonCustomTeamUserRoles
}

// GetDisableNonCustomTeamUserRolesOk returns a tuple with the DisableNonCustomTeamUserRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditingGeneralOrganizationSettings) GetDisableNonCustomTeamUserRolesOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableNonCustomTeamUserRoles) {
		return nil, false
	}
	return o.DisableNonCustomTeamUserRoles, true
}

// HasDisableNonCustomTeamUserRoles returns a boolean if a field has been set.
func (o *EditingGeneralOrganizationSettings) HasDisableNonCustomTeamUserRoles() bool {
	if o != nil && !IsNil(o.DisableNonCustomTeamUserRoles) {
		return true
	}

	return false
}

// SetDisableNonCustomTeamUserRoles gets a reference to the given bool and assigns it to the DisableNonCustomTeamUserRoles field.
func (o *EditingGeneralOrganizationSettings) SetDisableNonCustomTeamUserRoles(v bool) {
	o.DisableNonCustomTeamUserRoles = &v
}

func (o EditingGeneralOrganizationSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditingGeneralOrganizationSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.DefaultRoleId) {
		toSerialize["defaultRoleId"] = o.DefaultRoleId
	}
	if !IsNil(o.DependencySignatures) {
		toSerialize["dependencySignatures"] = o.DependencySignatures
	}
	if !IsNil(o.DisableNonCustomTeamUserRoles) {
		toSerialize["disableNonCustomTeamUserRoles"] = o.DisableNonCustomTeamUserRoles
	}
	return toSerialize, nil
}

type NullableEditingGeneralOrganizationSettings struct {
	value *EditingGeneralOrganizationSettings
	isSet bool
}

func (v NullableEditingGeneralOrganizationSettings) Get() *EditingGeneralOrganizationSettings {
	return v.value
}

func (v *NullableEditingGeneralOrganizationSettings) Set(val *EditingGeneralOrganizationSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableEditingGeneralOrganizationSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableEditingGeneralOrganizationSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditingGeneralOrganizationSettings(val *EditingGeneralOrganizationSettings) *NullableEditingGeneralOrganizationSettings {
	return &NullableEditingGeneralOrganizationSettings{value: val, isSet: true}
}

func (v NullableEditingGeneralOrganizationSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditingGeneralOrganizationSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


