/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.58
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner{}

// GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner struct for GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner
type GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner struct {
	Title *string `json:"title,omitempty"`
	LicenseId *string `json:"licenseId,omitempty"`
	Ignored *bool `json:"ignored,omitempty"`
	Url NullableString `json:"url,omitempty"`
	LicenseGroupId *int32 `json:"licenseGroupId,omitempty"`
	RevisionLicenseId *int32 `json:"revisionLicenseId,omitempty"`
	ProjectCorrectionId NullableInt32 `json:"projectCorrectionId,omitempty"`
	Group *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInnerGroup `json:"group,omitempty"`
}

// NewGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner instantiates a new GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner() *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner {
	this := GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner{}
	return &this
}

// NewGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInnerWithDefaults instantiates a new GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInnerWithDefaults() *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner {
	this := GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner{}
	return &this
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetTitle(v string) {
	o.Title = &v
}

// GetLicenseId returns the LicenseId field value if set, zero value otherwise.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetLicenseId() string {
	if o == nil || IsNil(o.LicenseId) {
		var ret string
		return ret
	}
	return *o.LicenseId
}

// GetLicenseIdOk returns a tuple with the LicenseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetLicenseIdOk() (*string, bool) {
	if o == nil || IsNil(o.LicenseId) {
		return nil, false
	}
	return o.LicenseId, true
}

// HasLicenseId returns a boolean if a field has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) HasLicenseId() bool {
	if o != nil && !IsNil(o.LicenseId) {
		return true
	}

	return false
}

// SetLicenseId gets a reference to the given string and assigns it to the LicenseId field.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetLicenseId(v string) {
	o.LicenseId = &v
}

// GetIgnored returns the Ignored field value if set, zero value otherwise.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetIgnored() bool {
	if o == nil || IsNil(o.Ignored) {
		var ret bool
		return ret
	}
	return *o.Ignored
}

// GetIgnoredOk returns a tuple with the Ignored field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetIgnoredOk() (*bool, bool) {
	if o == nil || IsNil(o.Ignored) {
		return nil, false
	}
	return o.Ignored, true
}

// HasIgnored returns a boolean if a field has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) HasIgnored() bool {
	if o != nil && !IsNil(o.Ignored) {
		return true
	}

	return false
}

// SetIgnored gets a reference to the given bool and assigns it to the Ignored field.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetIgnored(v bool) {
	o.Ignored = &v
}

// GetUrl returns the Url field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetUrl() string {
	if o == nil || IsNil(o.Url.Get()) {
		var ret string
		return ret
	}
	return *o.Url.Get()
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Url.Get(), o.Url.IsSet()
}

// HasUrl returns a boolean if a field has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) HasUrl() bool {
	if o != nil && o.Url.IsSet() {
		return true
	}

	return false
}

// SetUrl gets a reference to the given NullableString and assigns it to the Url field.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetUrl(v string) {
	o.Url.Set(&v)
}
// SetUrlNil sets the value for Url to be an explicit nil
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetUrlNil() {
	o.Url.Set(nil)
}

// UnsetUrl ensures that no value is present for Url, not even an explicit nil
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) UnsetUrl() {
	o.Url.Unset()
}

// GetLicenseGroupId returns the LicenseGroupId field value if set, zero value otherwise.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetLicenseGroupId() int32 {
	if o == nil || IsNil(o.LicenseGroupId) {
		var ret int32
		return ret
	}
	return *o.LicenseGroupId
}

// GetLicenseGroupIdOk returns a tuple with the LicenseGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetLicenseGroupIdOk() (*int32, bool) {
	if o == nil || IsNil(o.LicenseGroupId) {
		return nil, false
	}
	return o.LicenseGroupId, true
}

// HasLicenseGroupId returns a boolean if a field has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) HasLicenseGroupId() bool {
	if o != nil && !IsNil(o.LicenseGroupId) {
		return true
	}

	return false
}

// SetLicenseGroupId gets a reference to the given int32 and assigns it to the LicenseGroupId field.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetLicenseGroupId(v int32) {
	o.LicenseGroupId = &v
}

// GetRevisionLicenseId returns the RevisionLicenseId field value if set, zero value otherwise.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetRevisionLicenseId() int32 {
	if o == nil || IsNil(o.RevisionLicenseId) {
		var ret int32
		return ret
	}
	return *o.RevisionLicenseId
}

// GetRevisionLicenseIdOk returns a tuple with the RevisionLicenseId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetRevisionLicenseIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RevisionLicenseId) {
		return nil, false
	}
	return o.RevisionLicenseId, true
}

// HasRevisionLicenseId returns a boolean if a field has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) HasRevisionLicenseId() bool {
	if o != nil && !IsNil(o.RevisionLicenseId) {
		return true
	}

	return false
}

// SetRevisionLicenseId gets a reference to the given int32 and assigns it to the RevisionLicenseId field.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetRevisionLicenseId(v int32) {
	o.RevisionLicenseId = &v
}

// GetProjectCorrectionId returns the ProjectCorrectionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetProjectCorrectionId() int32 {
	if o == nil || IsNil(o.ProjectCorrectionId.Get()) {
		var ret int32
		return ret
	}
	return *o.ProjectCorrectionId.Get()
}

// GetProjectCorrectionIdOk returns a tuple with the ProjectCorrectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetProjectCorrectionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProjectCorrectionId.Get(), o.ProjectCorrectionId.IsSet()
}

// HasProjectCorrectionId returns a boolean if a field has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) HasProjectCorrectionId() bool {
	if o != nil && o.ProjectCorrectionId.IsSet() {
		return true
	}

	return false
}

// SetProjectCorrectionId gets a reference to the given NullableInt32 and assigns it to the ProjectCorrectionId field.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetProjectCorrectionId(v int32) {
	o.ProjectCorrectionId.Set(&v)
}
// SetProjectCorrectionIdNil sets the value for ProjectCorrectionId to be an explicit nil
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetProjectCorrectionIdNil() {
	o.ProjectCorrectionId.Set(nil)
}

// UnsetProjectCorrectionId ensures that no value is present for ProjectCorrectionId, not even an explicit nil
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) UnsetProjectCorrectionId() {
	o.ProjectCorrectionId.Unset()
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetGroup() GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInnerGroup {
	if o == nil || IsNil(o.Group) {
		var ret GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInnerGroup
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) GetGroupOk() (*GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInnerGroup, bool) {
	if o == nil || IsNil(o.Group) {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) HasGroup() bool {
	if o != nil && !IsNil(o.Group) {
		return true
	}

	return false
}

// SetGroup gets a reference to the given GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInnerGroup and assigns it to the Group field.
func (o *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) SetGroup(v GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInnerGroup) {
	o.Group = &v
}

func (o GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.LicenseId) {
		toSerialize["licenseId"] = o.LicenseId
	}
	if !IsNil(o.Ignored) {
		toSerialize["ignored"] = o.Ignored
	}
	if o.Url.IsSet() {
		toSerialize["url"] = o.Url.Get()
	}
	if !IsNil(o.LicenseGroupId) {
		toSerialize["licenseGroupId"] = o.LicenseGroupId
	}
	if !IsNil(o.RevisionLicenseId) {
		toSerialize["revisionLicenseId"] = o.RevisionLicenseId
	}
	if o.ProjectCorrectionId.IsSet() {
		toSerialize["projectCorrectionId"] = o.ProjectCorrectionId.Get()
	}
	if !IsNil(o.Group) {
		toSerialize["group"] = o.Group
	}
	return toSerialize, nil
}

type NullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner struct {
	value *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner
	isSet bool
}

func (v NullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) Get() *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner {
	return v.value
}

func (v *NullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) Set(val *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner(val *GetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) *NullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner {
	return &NullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner{value: val, isSet: true}
}

func (v NullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGlobalDependency200ResponseDependencyAllOfGroupedLicensesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


