/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.67
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// GetIssueCountsTeamIdParameterInner - struct for GetIssueCountsTeamIdParameterInner
type GetIssueCountsTeamIdParameterInner struct {
	Float32 *float32
	String *string
}

// float32AsGetIssueCountsTeamIdParameterInner is a convenience function that returns float32 wrapped in GetIssueCountsTeamIdParameterInner
func Float32AsGetIssueCountsTeamIdParameterInner(v *float32) GetIssueCountsTeamIdParameterInner {
	return GetIssueCountsTeamIdParameterInner{
		Float32: v,
	}
}

// stringAsGetIssueCountsTeamIdParameterInner is a convenience function that returns string wrapped in GetIssueCountsTeamIdParameterInner
func StringAsGetIssueCountsTeamIdParameterInner(v *string) GetIssueCountsTeamIdParameterInner {
	return GetIssueCountsTeamIdParameterInner{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetIssueCountsTeamIdParameterInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			if err = validator.Validate(dst.Float32); err != nil {
				dst.Float32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Float32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetIssueCountsTeamIdParameterInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		if err != nil {
			return fmt.Errorf("data failed to match schemas in oneOf(GetIssueCountsTeamIdParameterInner): %v", err)
		}

		return fmt.Errorf("data failed to match schemas in oneOf(GetIssueCountsTeamIdParameterInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetIssueCountsTeamIdParameterInner) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetIssueCountsTeamIdParameterInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetIssueCountsTeamIdParameterInner) GetActualInstanceValue() (interface{}) {
	if obj.Float32 != nil {
		return *obj.Float32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableGetIssueCountsTeamIdParameterInner struct {
	value *GetIssueCountsTeamIdParameterInner
	isSet bool
}

func (v NullableGetIssueCountsTeamIdParameterInner) Get() *GetIssueCountsTeamIdParameterInner {
	return v.value
}

func (v *NullableGetIssueCountsTeamIdParameterInner) Set(val *GetIssueCountsTeamIdParameterInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIssueCountsTeamIdParameterInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIssueCountsTeamIdParameterInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIssueCountsTeamIdParameterInner(val *GetIssueCountsTeamIdParameterInner) *NullableGetIssueCountsTeamIdParameterInner {
	return &NullableGetIssueCountsTeamIdParameterInner{value: val, isSet: true}
}

func (v NullableGetIssueCountsTeamIdParameterInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIssueCountsTeamIdParameterInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


