/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.46
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner{}

// GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner struct for GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner
type GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner struct {
	Id *int32 `json:"id,omitempty"`
}

// NewGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner instantiates a new GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner() *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner {
	this := GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner{}
	return &this
}

// NewGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInnerWithDefaults instantiates a new GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInnerWithDefaults() *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner {
	this := GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) SetId(v int32) {
	o.Id = &v
}

func (o GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner struct {
	value *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner
	isSet bool
}

func (v NullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) Get() *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner {
	return v.value
}

func (v *NullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) Set(val *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner(val *GetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) *NullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner {
	return &NullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner{value: val, isSet: true}
}

func (v NullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetReleaseGroupReleaseScans200ResponseInnerAllOfRevisionScansInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


