/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.30.21
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateOIDCTrustRelationship200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOIDCTrustRelationship200Response{}

// CreateOIDCTrustRelationship200Response struct for CreateOIDCTrustRelationship200Response
type CreateOIDCTrustRelationship200Response struct {
	// The unique identifier of the OIDC Trust Relationship
	Id int32 `json:"id"`
	// The ID of the organization this trust relationship belongs to
	OrganizationId int32 `json:"organizationId"`
	// The ID of the user associated with this trust relationship
	UserId int32 `json:"userId"`
	// The ID of the OIDC Provider this trust relationship uses
	ProviderId int32 `json:"providerId"`
	// The scope level of the trust relationship
	Scope *string `json:"scope,omitempty"`
	// The ID associated with the scope
	ScopeId *string `json:"scopeId,omitempty"`
	// Array of valid audiences for this trust relationship (max 5)
	Audiences []string `json:"audiences"`
	// Array of claim objects. Must contain at least one object with claim: \"sub\". Additional objects with other claims are optional. 
	RequiredClaims []CreateOIDCTrustRelationshipRequestRequiredClaimsInner `json:"requiredClaims"`
	// When the trust relationship was created
	CreatedAt time.Time `json:"createdAt"`
	// When the trust relationship was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

type _CreateOIDCTrustRelationship200Response CreateOIDCTrustRelationship200Response

// NewCreateOIDCTrustRelationship200Response instantiates a new CreateOIDCTrustRelationship200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOIDCTrustRelationship200Response(id int32, organizationId int32, userId int32, providerId int32, audiences []string, requiredClaims []CreateOIDCTrustRelationshipRequestRequiredClaimsInner, createdAt time.Time, updatedAt time.Time) *CreateOIDCTrustRelationship200Response {
	this := CreateOIDCTrustRelationship200Response{}
	this.Id = id
	this.OrganizationId = organizationId
	this.UserId = userId
	this.ProviderId = providerId
	this.Audiences = audiences
	this.RequiredClaims = requiredClaims
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewCreateOIDCTrustRelationship200ResponseWithDefaults instantiates a new CreateOIDCTrustRelationship200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOIDCTrustRelationship200ResponseWithDefaults() *CreateOIDCTrustRelationship200Response {
	this := CreateOIDCTrustRelationship200Response{}
	return &this
}

// GetId returns the Id field value
func (o *CreateOIDCTrustRelationship200Response) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CreateOIDCTrustRelationship200Response) SetId(v int32) {
	o.Id = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *CreateOIDCTrustRelationship200Response) GetOrganizationId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetOrganizationIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *CreateOIDCTrustRelationship200Response) SetOrganizationId(v int32) {
	o.OrganizationId = v
}

// GetUserId returns the UserId field value
func (o *CreateOIDCTrustRelationship200Response) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *CreateOIDCTrustRelationship200Response) SetUserId(v int32) {
	o.UserId = v
}

// GetProviderId returns the ProviderId field value
func (o *CreateOIDCTrustRelationship200Response) GetProviderId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetProviderIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderId, true
}

// SetProviderId sets field value
func (o *CreateOIDCTrustRelationship200Response) SetProviderId(v int32) {
	o.ProviderId = v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *CreateOIDCTrustRelationship200Response) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *CreateOIDCTrustRelationship200Response) HasScope() bool {
	if o != nil && !IsNil(o.Scope) {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *CreateOIDCTrustRelationship200Response) SetScope(v string) {
	o.Scope = &v
}

// GetScopeId returns the ScopeId field value if set, zero value otherwise.
func (o *CreateOIDCTrustRelationship200Response) GetScopeId() string {
	if o == nil || IsNil(o.ScopeId) {
		var ret string
		return ret
	}
	return *o.ScopeId
}

// GetScopeIdOk returns a tuple with the ScopeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetScopeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ScopeId) {
		return nil, false
	}
	return o.ScopeId, true
}

// HasScopeId returns a boolean if a field has been set.
func (o *CreateOIDCTrustRelationship200Response) HasScopeId() bool {
	if o != nil && !IsNil(o.ScopeId) {
		return true
	}

	return false
}

// SetScopeId gets a reference to the given string and assigns it to the ScopeId field.
func (o *CreateOIDCTrustRelationship200Response) SetScopeId(v string) {
	o.ScopeId = &v
}

// GetAudiences returns the Audiences field value
func (o *CreateOIDCTrustRelationship200Response) GetAudiences() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetAudiencesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Audiences, true
}

// SetAudiences sets field value
func (o *CreateOIDCTrustRelationship200Response) SetAudiences(v []string) {
	o.Audiences = v
}

// GetRequiredClaims returns the RequiredClaims field value
func (o *CreateOIDCTrustRelationship200Response) GetRequiredClaims() []CreateOIDCTrustRelationshipRequestRequiredClaimsInner {
	if o == nil {
		var ret []CreateOIDCTrustRelationshipRequestRequiredClaimsInner
		return ret
	}

	return o.RequiredClaims
}

// GetRequiredClaimsOk returns a tuple with the RequiredClaims field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetRequiredClaimsOk() ([]CreateOIDCTrustRelationshipRequestRequiredClaimsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.RequiredClaims, true
}

// SetRequiredClaims sets field value
func (o *CreateOIDCTrustRelationship200Response) SetRequiredClaims(v []CreateOIDCTrustRelationshipRequestRequiredClaimsInner) {
	o.RequiredClaims = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CreateOIDCTrustRelationship200Response) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CreateOIDCTrustRelationship200Response) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CreateOIDCTrustRelationship200Response) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCTrustRelationship200Response) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CreateOIDCTrustRelationship200Response) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o CreateOIDCTrustRelationship200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOIDCTrustRelationship200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["userId"] = o.UserId
	toSerialize["providerId"] = o.ProviderId
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.ScopeId) {
		toSerialize["scopeId"] = o.ScopeId
	}
	toSerialize["audiences"] = o.Audiences
	toSerialize["requiredClaims"] = o.RequiredClaims
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *CreateOIDCTrustRelationship200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"organizationId",
		"userId",
		"providerId",
		"audiences",
		"requiredClaims",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOIDCTrustRelationship200Response := _CreateOIDCTrustRelationship200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOIDCTrustRelationship200Response)

	if err != nil {
		return err
	}

	*o = CreateOIDCTrustRelationship200Response(varCreateOIDCTrustRelationship200Response)

	return err
}

type NullableCreateOIDCTrustRelationship200Response struct {
	value *CreateOIDCTrustRelationship200Response
	isSet bool
}

func (v NullableCreateOIDCTrustRelationship200Response) Get() *CreateOIDCTrustRelationship200Response {
	return v.value
}

func (v *NullableCreateOIDCTrustRelationship200Response) Set(val *CreateOIDCTrustRelationship200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOIDCTrustRelationship200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOIDCTrustRelationship200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOIDCTrustRelationship200Response(val *CreateOIDCTrustRelationship200Response) *NullableCreateOIDCTrustRelationship200Response {
	return &NullableCreateOIDCTrustRelationship200Response{value: val, isSet: true}
}

func (v NullableCreateOIDCTrustRelationship200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOIDCTrustRelationship200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


