/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.32.20
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
)

// checks if the GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase{}

// GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase struct for GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase
type GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase struct {
	Licenses []string `json:"licenses,omitempty"`
	Justification *string `json:"justification,omitempty"`
}

// NewGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase instantiates a new GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase() *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase {
	this := GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase{}
	return &this
}

// NewGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBaseWithDefaults instantiates a new GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBaseWithDefaults() *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase {
	this := GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase{}
	return &this
}

// GetLicenses returns the Licenses field value if set, zero value otherwise.
func (o *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) GetLicenses() []string {
	if o == nil || IsNil(o.Licenses) {
		var ret []string
		return ret
	}
	return o.Licenses
}

// GetLicensesOk returns a tuple with the Licenses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) GetLicensesOk() ([]string, bool) {
	if o == nil || IsNil(o.Licenses) {
		return nil, false
	}
	return o.Licenses, true
}

// HasLicenses returns a boolean if a field has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) HasLicenses() bool {
	if o != nil && !IsNil(o.Licenses) {
		return true
	}

	return false
}

// SetLicenses gets a reference to the given []string and assigns it to the Licenses field.
func (o *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) SetLicenses(v []string) {
	o.Licenses = v
}

// GetJustification returns the Justification field value if set, zero value otherwise.
func (o *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) GetJustification() string {
	if o == nil || IsNil(o.Justification) {
		var ret string
		return ret
	}
	return *o.Justification
}

// GetJustificationOk returns a tuple with the Justification field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) GetJustificationOk() (*string, bool) {
	if o == nil || IsNil(o.Justification) {
		return nil, false
	}
	return o.Justification, true
}

// HasJustification returns a boolean if a field has been set.
func (o *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) HasJustification() bool {
	if o != nil && !IsNil(o.Justification) {
		return true
	}

	return false
}

// SetJustification gets a reference to the given string and assigns it to the Justification field.
func (o *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) SetJustification(v string) {
	o.Justification = &v
}

func (o GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Licenses) {
		toSerialize["licenses"] = o.Licenses
	}
	if !IsNil(o.Justification) {
		toSerialize["justification"] = o.Justification
	}
	return toSerialize, nil
}

type NullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase struct {
	value *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase
	isSet bool
}

func (v NullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) Get() *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase {
	return v.value
}

func (v *NullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) Set(val *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) {
	v.value = val
	v.isSet = true
}

func (v NullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) IsSet() bool {
	return v.isSet
}

func (v *NullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase(val *GetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) *NullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase {
	return &NullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase{value: val, isSet: true}
}

func (v NullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetProjectDependencies200ResponseDependenciesInnerConcludedLicensesBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


