/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.33.15
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOIDCProviderRequestOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOIDCProviderRequestOneOf{}

// CreateOIDCProviderRequestOneOf struct for CreateOIDCProviderRequestOneOf
type CreateOIDCProviderRequestOneOf struct {
	// The issuer URL of the OIDC Provider
	Issuer string `json:"issuer"`
	// The scope level of the OIDC Provider
	Scope string `json:"scope"`
	// The ID of the team
	ScopeId int32 `json:"scopeId"`
}

type _CreateOIDCProviderRequestOneOf CreateOIDCProviderRequestOneOf

// NewCreateOIDCProviderRequestOneOf instantiates a new CreateOIDCProviderRequestOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOIDCProviderRequestOneOf(issuer string, scope string, scopeId int32) *CreateOIDCProviderRequestOneOf {
	this := CreateOIDCProviderRequestOneOf{}
	this.Issuer = issuer
	this.Scope = scope
	this.ScopeId = scopeId
	return &this
}

// NewCreateOIDCProviderRequestOneOfWithDefaults instantiates a new CreateOIDCProviderRequestOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOIDCProviderRequestOneOfWithDefaults() *CreateOIDCProviderRequestOneOf {
	this := CreateOIDCProviderRequestOneOf{}
	return &this
}

// GetIssuer returns the Issuer field value
func (o *CreateOIDCProviderRequestOneOf) GetIssuer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Issuer
}

// GetIssuerOk returns a tuple with the Issuer field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCProviderRequestOneOf) GetIssuerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Issuer, true
}

// SetIssuer sets field value
func (o *CreateOIDCProviderRequestOneOf) SetIssuer(v string) {
	o.Issuer = v
}

// GetScope returns the Scope field value
func (o *CreateOIDCProviderRequestOneOf) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCProviderRequestOneOf) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *CreateOIDCProviderRequestOneOf) SetScope(v string) {
	o.Scope = v
}

// GetScopeId returns the ScopeId field value
func (o *CreateOIDCProviderRequestOneOf) GetScopeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ScopeId
}

// GetScopeIdOk returns a tuple with the ScopeId field value
// and a boolean to check if the value has been set.
func (o *CreateOIDCProviderRequestOneOf) GetScopeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScopeId, true
}

// SetScopeId sets field value
func (o *CreateOIDCProviderRequestOneOf) SetScopeId(v int32) {
	o.ScopeId = v
}

func (o CreateOIDCProviderRequestOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOIDCProviderRequestOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["issuer"] = o.Issuer
	toSerialize["scope"] = o.Scope
	toSerialize["scopeId"] = o.ScopeId
	return toSerialize, nil
}

func (o *CreateOIDCProviderRequestOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"issuer",
		"scope",
		"scopeId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOIDCProviderRequestOneOf := _CreateOIDCProviderRequestOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOIDCProviderRequestOneOf)

	if err != nil {
		return err
	}

	*o = CreateOIDCProviderRequestOneOf(varCreateOIDCProviderRequestOneOf)

	return err
}

type NullableCreateOIDCProviderRequestOneOf struct {
	value *CreateOIDCProviderRequestOneOf
	isSet bool
}

func (v NullableCreateOIDCProviderRequestOneOf) Get() *CreateOIDCProviderRequestOneOf {
	return v.value
}

func (v *NullableCreateOIDCProviderRequestOneOf) Set(val *CreateOIDCProviderRequestOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOIDCProviderRequestOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOIDCProviderRequestOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOIDCProviderRequestOneOf(val *CreateOIDCProviderRequestOneOf) *NullableCreateOIDCProviderRequestOneOf {
	return &NullableCreateOIDCProviderRequestOneOf{value: val, isSet: true}
}

func (v NullableCreateOIDCProviderRequestOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOIDCProviderRequestOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


