/*
FOSSA API

OpenAPI Specification for public FOSSA APIs

API version: 4.34.94
Contact: support@fossa.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package fossa

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ListFossabotDependencyUpgradePRs200ResponseNodesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListFossabotDependencyUpgradePRs200ResponseNodesInner{}

// ListFossabotDependencyUpgradePRs200ResponseNodesInner One fossabot dependency-upgrade PR row on the project PRs tab.
type ListFossabotDependencyUpgradePRs200ResponseNodesInner struct {
	Title string `json:"title"`
	PrNumber NullableInt32 `json:"prNumber"`
	VcsUrl NullableString `json:"vcsUrl"`
	// PR detail page in the fossabot app. Null when fossabot did not give one.
	FossabotUrl NullableString `json:"fossabotUrl"`
	State string `json:"state"`
	AnalysisBadge NullableString `json:"analysisBadge"`
	// FOSSA user id of the initiator; null for automated PRs.
	InitiatedByUserId NullableInt32 `json:"initiatedByUserId"`
	// Display name of the initiator; null for automated PRs and for ids with no user in the calling organization. 
	InitiatedByName NullableString `json:"initiatedByName"`
	OpenedAt time.Time `json:"openedAt"`
	ClosedAt NullableTime `json:"closedAt"`
	MergedAt NullableTime `json:"mergedAt"`
}

type _ListFossabotDependencyUpgradePRs200ResponseNodesInner ListFossabotDependencyUpgradePRs200ResponseNodesInner

// NewListFossabotDependencyUpgradePRs200ResponseNodesInner instantiates a new ListFossabotDependencyUpgradePRs200ResponseNodesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListFossabotDependencyUpgradePRs200ResponseNodesInner(title string, prNumber NullableInt32, vcsUrl NullableString, fossabotUrl NullableString, state string, analysisBadge NullableString, initiatedByUserId NullableInt32, initiatedByName NullableString, openedAt time.Time, closedAt NullableTime, mergedAt NullableTime) *ListFossabotDependencyUpgradePRs200ResponseNodesInner {
	this := ListFossabotDependencyUpgradePRs200ResponseNodesInner{}
	this.Title = title
	this.PrNumber = prNumber
	this.VcsUrl = vcsUrl
	this.FossabotUrl = fossabotUrl
	this.State = state
	this.AnalysisBadge = analysisBadge
	this.InitiatedByUserId = initiatedByUserId
	this.InitiatedByName = initiatedByName
	this.OpenedAt = openedAt
	this.ClosedAt = closedAt
	this.MergedAt = mergedAt
	return &this
}

// NewListFossabotDependencyUpgradePRs200ResponseNodesInnerWithDefaults instantiates a new ListFossabotDependencyUpgradePRs200ResponseNodesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListFossabotDependencyUpgradePRs200ResponseNodesInnerWithDefaults() *ListFossabotDependencyUpgradePRs200ResponseNodesInner {
	this := ListFossabotDependencyUpgradePRs200ResponseNodesInner{}
	return &this
}

// GetTitle returns the Title field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetTitle(v string) {
	o.Title = v
}

// GetPrNumber returns the PrNumber field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetPrNumber() int32 {
	if o == nil || o.PrNumber.Get() == nil {
		var ret int32
		return ret
	}

	return *o.PrNumber.Get()
}

// GetPrNumberOk returns a tuple with the PrNumber field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetPrNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrNumber.Get(), o.PrNumber.IsSet()
}

// SetPrNumber sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetPrNumber(v int32) {
	o.PrNumber.Set(&v)
}

// GetVcsUrl returns the VcsUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetVcsUrl() string {
	if o == nil || o.VcsUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.VcsUrl.Get()
}

// GetVcsUrlOk returns a tuple with the VcsUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetVcsUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.VcsUrl.Get(), o.VcsUrl.IsSet()
}

// SetVcsUrl sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetVcsUrl(v string) {
	o.VcsUrl.Set(&v)
}

// GetFossabotUrl returns the FossabotUrl field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetFossabotUrl() string {
	if o == nil || o.FossabotUrl.Get() == nil {
		var ret string
		return ret
	}

	return *o.FossabotUrl.Get()
}

// GetFossabotUrlOk returns a tuple with the FossabotUrl field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetFossabotUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FossabotUrl.Get(), o.FossabotUrl.IsSet()
}

// SetFossabotUrl sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetFossabotUrl(v string) {
	o.FossabotUrl.Set(&v)
}

// GetState returns the State field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetState(v string) {
	o.State = v
}

// GetAnalysisBadge returns the AnalysisBadge field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetAnalysisBadge() string {
	if o == nil || o.AnalysisBadge.Get() == nil {
		var ret string
		return ret
	}

	return *o.AnalysisBadge.Get()
}

// GetAnalysisBadgeOk returns a tuple with the AnalysisBadge field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetAnalysisBadgeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AnalysisBadge.Get(), o.AnalysisBadge.IsSet()
}

// SetAnalysisBadge sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetAnalysisBadge(v string) {
	o.AnalysisBadge.Set(&v)
}

// GetInitiatedByUserId returns the InitiatedByUserId field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetInitiatedByUserId() int32 {
	if o == nil || o.InitiatedByUserId.Get() == nil {
		var ret int32
		return ret
	}

	return *o.InitiatedByUserId.Get()
}

// GetInitiatedByUserIdOk returns a tuple with the InitiatedByUserId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetInitiatedByUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.InitiatedByUserId.Get(), o.InitiatedByUserId.IsSet()
}

// SetInitiatedByUserId sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetInitiatedByUserId(v int32) {
	o.InitiatedByUserId.Set(&v)
}

// GetInitiatedByName returns the InitiatedByName field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetInitiatedByName() string {
	if o == nil || o.InitiatedByName.Get() == nil {
		var ret string
		return ret
	}

	return *o.InitiatedByName.Get()
}

// GetInitiatedByNameOk returns a tuple with the InitiatedByName field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetInitiatedByNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.InitiatedByName.Get(), o.InitiatedByName.IsSet()
}

// SetInitiatedByName sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetInitiatedByName(v string) {
	o.InitiatedByName.Set(&v)
}

// GetOpenedAt returns the OpenedAt field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetOpenedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.OpenedAt
}

// GetOpenedAtOk returns a tuple with the OpenedAt field value
// and a boolean to check if the value has been set.
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetOpenedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OpenedAt, true
}

// SetOpenedAt sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetOpenedAt(v time.Time) {
	o.OpenedAt = v
}

// GetClosedAt returns the ClosedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetClosedAt() time.Time {
	if o == nil || o.ClosedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ClosedAt.Get()
}

// GetClosedAtOk returns a tuple with the ClosedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetClosedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClosedAt.Get(), o.ClosedAt.IsSet()
}

// SetClosedAt sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetClosedAt(v time.Time) {
	o.ClosedAt.Set(&v)
}

// GetMergedAt returns the MergedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetMergedAt() time.Time {
	if o == nil || o.MergedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.MergedAt.Get()
}

// GetMergedAtOk returns a tuple with the MergedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) GetMergedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.MergedAt.Get(), o.MergedAt.IsSet()
}

// SetMergedAt sets field value
func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) SetMergedAt(v time.Time) {
	o.MergedAt.Set(&v)
}

func (o ListFossabotDependencyUpgradePRs200ResponseNodesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListFossabotDependencyUpgradePRs200ResponseNodesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["title"] = o.Title
	toSerialize["prNumber"] = o.PrNumber.Get()
	toSerialize["vcsUrl"] = o.VcsUrl.Get()
	toSerialize["fossabotUrl"] = o.FossabotUrl.Get()
	toSerialize["state"] = o.State
	toSerialize["analysisBadge"] = o.AnalysisBadge.Get()
	toSerialize["initiatedByUserId"] = o.InitiatedByUserId.Get()
	toSerialize["initiatedByName"] = o.InitiatedByName.Get()
	toSerialize["openedAt"] = o.OpenedAt
	toSerialize["closedAt"] = o.ClosedAt.Get()
	toSerialize["mergedAt"] = o.MergedAt.Get()
	return toSerialize, nil
}

func (o *ListFossabotDependencyUpgradePRs200ResponseNodesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"title",
		"prNumber",
		"vcsUrl",
		"fossabotUrl",
		"state",
		"analysisBadge",
		"initiatedByUserId",
		"initiatedByName",
		"openedAt",
		"closedAt",
		"mergedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListFossabotDependencyUpgradePRs200ResponseNodesInner := _ListFossabotDependencyUpgradePRs200ResponseNodesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListFossabotDependencyUpgradePRs200ResponseNodesInner)

	if err != nil {
		return err
	}

	*o = ListFossabotDependencyUpgradePRs200ResponseNodesInner(varListFossabotDependencyUpgradePRs200ResponseNodesInner)

	return err
}

type NullableListFossabotDependencyUpgradePRs200ResponseNodesInner struct {
	value *ListFossabotDependencyUpgradePRs200ResponseNodesInner
	isSet bool
}

func (v NullableListFossabotDependencyUpgradePRs200ResponseNodesInner) Get() *ListFossabotDependencyUpgradePRs200ResponseNodesInner {
	return v.value
}

func (v *NullableListFossabotDependencyUpgradePRs200ResponseNodesInner) Set(val *ListFossabotDependencyUpgradePRs200ResponseNodesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListFossabotDependencyUpgradePRs200ResponseNodesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListFossabotDependencyUpgradePRs200ResponseNodesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListFossabotDependencyUpgradePRs200ResponseNodesInner(val *ListFossabotDependencyUpgradePRs200ResponseNodesInner) *NullableListFossabotDependencyUpgradePRs200ResponseNodesInner {
	return &NullableListFossabotDependencyUpgradePRs200ResponseNodesInner{value: val, isSet: true}
}

func (v NullableListFossabotDependencyUpgradePRs200ResponseNodesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListFossabotDependencyUpgradePRs200ResponseNodesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


